---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  test.conf: |
    title = "myConfig"
    enableAwesome = "true"
    version = {{ .Chart.Version | quote }}
