---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: apps
    repoURL: https://github.com/yellowhat/argocd
    targetRevision: HEAD
    directory:
      recurse: false
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: false  # Disabled due to high cpu usage
    # retry:
    #   limit: 5
    #   backoff:
    #     duration: 5s
    #     maxDuration: 3m0s
    #     factor: 2
    syncOptions:
      - CreateNamespace=true
      # - Replace=true
