{
 "title": "Kepler-exporter",
 "description": "Metrics from kepler",
 "tags": [ "kepler" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kepler_container_package_joules_total, container_namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}, pod_name)"
    }
   },
   { "name": "watt_per_second_to_kWh", "query": "0.000000277777777777778" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Power in Namespace: $namespace",
   "type": "stat",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "PKG"
    },
    {
     "expr": "sum(irate(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "DRAM"
    },
    {
     "expr": "sum(irate(kepler_container_other_host_components_joules_total{container_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "OTHER"
    },
    {
     "expr": "sum(irate(kepler_container_gpu_joules_total{container_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": " GPU"
    }
   ]
  },
  {
   "title": "Energy (PKG+DRAM) by Namespace per day",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container_namespace) (\n  (\n    increase(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[1h])\n    *\n    $watt_per_second_to_kWh\n  )\n  *\n  (\n    count_over_time(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[24h])\n    /\n    count_over_time(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[1h])\n  )\n)\n+\nsum by (container_namespace) (\n  (\n    increase(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[1h])\n    *\n    $watt_per_second_to_kWh\n  )\n  *\n  (\n    count_over_time(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[24h])\n    /\n    count_over_time(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[1h])\n  )\n)",
     "legendFormat": "{{ container_namespace }}"
    }
   ]
  },
  {
   "title": "Energy (PKG+DRAM) by Namespace per day",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container_namespace) (\n  (\n    increase(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[1h])\n    *\n    $watt_per_second_to_kWh\n  )\n  *\n  (\n    count_over_time(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[24h])\n    /\n    count_over_time(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[1h])\n  )\n)\n+\nsum by (container_namespace) (\n  (\n    increase(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[1h])\n    *\n    $watt_per_second_to_kWh\n  )\n  *\n  (\n    count_over_time(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[24h])\n    /\n    count_over_time(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[1h])\n  )\n)",
     "legendFormat": "{{container_namespace}}"
    }
   ]
  },
  { "title": "Energy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Energy per day",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum (increase(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[24h]))\n*\n$watt_per_second_to_kWh",
     "legendFormat": "PKG"
    },
    {
     "expr": "sum (increase(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[24h]))\n*\n$watt_per_second_to_kWh",
     "legendFormat": "DRAM"
    },
    {
     "expr": "sum (increase(kepler_container_other_host_components_joules_total{container_namespace=~\"$namespace\"}[24h]))\n*\n$watt_per_second_to_kWh",
     "legendFormat": "OTHER"
    },
    {
     "expr": "sum (increase(kepler_container_gpu_joules_total{container_namespace=~\"$namespace\"}[24h]))\n*\n$watt_per_second_to_kWh",
     "legendFormat": "GPU"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Pod/Process Power Consumption in Namespace: $namespace",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (pod_name, container_namespace) (irate(kepler_container_package_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[5m]))",
     "legendFormat": "{{pod_name}} / {{container_namespace}} / PKG"
    },
    {
     "expr": "sum by (pod_name, container_namespace) (irate(kepler_container_dram_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[5m]))",
     "legendFormat": "{{pod_name}} / {{container_namespace}} / DRAM"
    },
    {
     "expr": "sum by (pod_name, container_namespace) (irate(kepler_container_other_host_components_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[5m]))",
     "legendFormat": "{{pod_name}} / {{container_namespace}} / OTHER"
    },
    {
     "expr": "sum by (pod_name, container_namespace) (irate(kepler_container_gpu_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[5m]))",
     "legendFormat": "{{pod_name}} / {{container_namespace}} / GPU"
    }
   ]
  },
  {
   "title": "Total Power Consumption in Namespace: $namespace",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(irate(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "PKG"
    },
    {
     "expr": "sum(irate(kepler_container_dram_joules_total{container_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "DRAM"
    },
    {
     "expr": "sum(irate(kepler_container_other_host_components_joules_total{container_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "OTHER"
    },
    {
     "expr": "sum(irate(kepler_container_gpu_joules_total{container_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": " GPU"
    }
   ]
  }
 ]
}