---
apiVersion: v2
name: system
description: Install system
home: https://gitlab.com/yellowhat-labs/mule/-/tree/main/charts/system
type: application
version: 4.8.46
appVersion: 4.8.46
icon: https://github.com/kubernetes/kubernetes/raw/master/logo/logo.png
sources:
  - https://github.com/bitnami-labs/sealed-secrets
  - https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
  - https://github.com/grafana/loki/tree/main/production/helm/loki
  - https://github.com/grafana/helm-charts/tree/main/charts/promtail
  - https://gitlab.com/yellowhat-labs/mule/-/tree/main/charts/system
maintainers:
  - name: yellowhat
    email: yellowhat@mailbox.org
dependencies:
  - name: kube-prometheus-stack
    version: 61.9.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: loki
    version: 6.10.0
    repository: https://grafana.github.io/helm-charts
  - name: promtail
    version: 6.16.4
    repository: https://grafana.github.io/helm-charts
  - name: sealed-secrets
    version: 2.16.1
    repository: https://bitnami-labs.github.io/sealed-secrets
