---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-smartctl
spec:
  groups:
    - name: custom-smartctl
      rules:
        - alert: SmartDeviceTemperatureWarning
          expr: 'smartctl_device_temperature > 60'
          for: 1m
          labels:
            severity: warning
          annotations:
            message: Device {{`{{ $labels.device }}`}} on instance {{`{{ $labels.instance }}`}} has high temperature

        - alert: SmartDeviceTemperatureCritical
          expr: 'smartctl_device_temperature > 80'
          for: 1m
          labels:
            severity: critical
          annotations:
            message: Device {{`{{ $labels.device }}`}} on instance {{`{{ $labels.instance }}`}} has critical temperature

        - alert: SmartDeviceStatus
          expr: 'sum(1 - smartctl_device_smart_status) != 0'
          for: 1m
          labels:
            severity: critical
          annotations:
            message: Device {{`{{ $labels.device }}`}} on instance {{`{{ $labels.instance }}`}} has critical status

        - alert: SmartDeviceErrorLog
          expr: 'sum(smartctl_device_num_err_log_entries) != 0'
          for: 1m
          labels:
            severity: critical
          annotations:
            message: Device {{`{{ $labels.device }}`}} on instance {{`{{ $labels.instance }}`}} has errors
