---
prometheus-smartctl-exporter:
  common:
    config:
      collect_not_more_than_period: 120s

  serviceMonitor:
    enabled: true
    interval: 120s
    scrapeTimeout: 30s

  prometheusRules:
    enabled: true
