---
# Source: system/charts/promtail/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system-promtail
  labels:
    helm.sh/chart: promtail-6.16.4
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: system
    app.kubernetes.io/version: "3.0.0"
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: system-promtail
    namespace: system
roleRef:
  kind: ClusterRole
  name: system-promtail
  apiGroup: rbac.authorization.k8s.io
