---
# Source: system/charts/promtail/templates/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system-promtail
  labels:
    helm.sh/chart: promtail-6.16.4
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: system
    app.kubernetes.io/version: "3.0.0"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs:
      - get
      - watch
      - list
