---
# Source: system/charts/promtail/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: system-promtail
  namespace: system
  labels:
    helm.sh/chart: promtail-6.16.4
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: system
    app.kubernetes.io/version: "3.0.0"
    app.kubernetes.io/managed-by: Helm
