{
 "title": "Golang",
 "description": "Metrics from golang applications",
 "tags": [ "golang" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(go_info,job)" } },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(go_info{job=\"$job\"}, pod)"
    }
   },
   {
    "name": "rate",
    "label": "Rate",
    "query": "1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Go Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_info{job=~\"$job\", pod=~\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_threads{job=~\"$job\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"$job\", pod=~\"$pod\"}"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=~\"$job\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{job=~\"$job\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "timeseries",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{job=~\"$job\", pod=~\"$pod\"}[$rate])"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "timeseries",
   "description": "Shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=~\"$job\", pod=~\"$pod\"}[$rate])"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"$job\", pod=~\"$pod\"}[$rate])"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=~\"$job\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=~\"$job\", pod=~\"$pod\"}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=~\"$job\", pod=~\"$pod\"}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=~\"$job\", pod=~\"$pod\"}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"$job\", pod=~\"$pod\"}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=~\"$job\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Memory in Off-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{job=~\"$job\", pod=~\"$pod\"}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{job=~\"$job\", pod=~\"$pod\"}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{job=~\"$job\", pod=~\"$pod\"}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{job=~\"$job\", pod=~\"$pod\"}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{job=~\"$job\", pod=~\"$pod\"}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{job=~\"$job\", pod=~\"$pod\"}"
    },
    {
     "expr": "go_memstats_other_sys_bytes{job=~\"$job\", pod=~\"$pod\"}",
     "legendFormat": "bytes of memory are used for other runtime allocations {pod={{kubernetes_pod_name}}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=~\"$job\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~\"$job\", pod=~\"$pod\"}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{job=~\"$job\", pod=~\"$pod\"}"
    }
   ]
  }
 ]
}