{
 "title": "Smartctl",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(smartctl_device_smart_status, instance)"
    }
   },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(smartctl_device_smart_status, device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_smart_status{instance=~'$instance'}",
     "legendFormat": "{{ instance }} |  {{ device }}"
    }
   ]
  },
  {
   "title": "Smartctl exit status",
   "type": "stat",
   "description": "Exit status of smartctl on device",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_smartctl_exit_status{instance=~'$instance', device=~'$device'}",
     "legendFormat": "{{ instance }} | {{ device }}"
    }
   ]
  },
  {
   "title": "Num Error log",
   "type": "stat",
   "description": "Contains the number of Error Information log entries over the life of the controller",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(smartctl_device_num_err_log_entries{instance=~'$instance', device=~'$device'}[3m])",
     "legendFormat": "{{ instance }} | {{ device }}"
    }
   ]
  },
  {
   "title": "Write % used",
   "type": "stat",
   "description": "Device write percentage used",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(smartctl_device_percentage_used{instance=~\"$instance\", device=~\"$device\"}[3m])",
     "legendFormat": "{{ instance }} | {{ device }}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "description": "Device temperature celsius",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_temperature{instance=~'$instance', device=~'$device'}",
     "legendFormat": "{{ instance }} | {{ device }}"
    }
   ]
  },
  {
   "title": "Power cycle count",
   "type": "stat",
   "description": "Device power cycle count",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(smartctl_device_power_cycle_count{instance=~'$instance', device=~'$device'}[3m])",
     "legendFormat": "{{ instance }} | {{ device }}"
    }
   ]
  },
  {
   "title": "Power on time",
   "type": "stat",
   "description": "Device power on seconds",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(smartctl_device_power_on_seconds{instance=~'$instance', device=~'$device'}[3m])",
     "legendFormat": "{{ instance }} | {{ device }}"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "stat",
   "description": "Device capacity in bytes",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_capacity_bytes{instance=~'$instance', device=~'$device'}",
     "legendFormat": "{{ instance }} | {{ device }}"
    }
   ]
  },
  {
   "title": "Interface speed",
   "type": "stat",
   "description": "Device interface speed, bits per second",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_interface_speed{instance=~'$instance', device=~'$device'}",
     "legendFormat": "{{ instance }} | {{ device }}"
    }
   ]
  },
  {
   "title": "Block size",
   "type": "stat",
   "description": "Device block size",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_block_size{instance=~'$instance', device=~'$device'}",
     "legendFormat": "{{ instance}} | {{ device }}"
    }
   ]
  },
  {
   "title": "Firmware version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device{instance=~'$instance', device=~'$device'}",
     "legendFormat": "{{ instance}} | {{ device }}"
    }
   ]
  },
  {
   "title": "Model name",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device{instance=~'$instance', device=~'$device'}",
     "legendFormat": "{{ instance}} | {{ device }}"
    }
   ]
  },
  {
   "title": "Critical warning",
   "type": "timeseries",
   "description": "Critical warning counter",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "smartctl_device_critical_warning{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{ instance }} | {{ device }}"
    }
   ]
  },
  {
   "title": "Media errors",
   "type": "timeseries",
   "description": "Media errors counter",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "smartctl_device_media_errors{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{ instance }} | {{ device }}"
    }
   ]
  },
  {
   "title": "Available spare",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "smartctl_device_available_spare{instance=~'$instance', device!~\"/dev/s.*\"}",
     "legendFormat": "{{ instance }} | {{ device }}"
    }
   ]
  },
  {
   "title": "smartctl_device_bytes_written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(smartctl_device_bytes_written{instance=~'$instance', device=~'$device'}[3m])",
     "legendFormat": "{{ instance }} | {{ device }}"
    }
   ]
  },
  {
   "title": "smartctl_device_bytes_read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(smartctl_device_bytes_read{instance=~'$instance', device=~'$device'}[3m])",
     "legendFormat": "{{ instance }} | {{ device }}"
    }
   ]
  }
 ]
}