{
 "title": "Tasmota",
 "description": "Metrics from tasmota devices",
 "tags": [ "tasmota" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Switch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "tasmota_relay1_state", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "State",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 22, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    { "expr": "tasmota_relay1_state", "legendFormat": "{{ instance }}" }
   ]
  },
  { "title": "Energy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Today",
   "type": "stat",
   "gridPos": { "h": 11, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tasmota_energy_power_kilowatts_daily",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 22, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "tasmota_energy_power_kilowatts_total",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Energy per day",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "delta(tasmota_energy_power_kilowatts_total[1d])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Energy per week",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "delta(tasmota_energy_power_kilowatts_total[1w])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "tasmota_energy_power_active_watts",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "tasmota_energy_current_amperes", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "tasmota_energy_voltage_volts", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Reactive Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "voltampreact" } },
   "targets": [
    { "expr": "tasmota_sensors_reactivepower_", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Apparent Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    { "expr": "tasmota_sensors_apparentpower_", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Power Factor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "tasmota_sensors_factor_", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "tasmota_uptime_seconds", "legendFormat": "{{ instance }}" }
     ]
    },
    {
     "title": "Number of boot",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "tasmota_boot_count", "legendFormat": "{{ instance }}" }
     ]
    },
    {
     "title": "Number of flash writes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "tasmota_flash_writes_total", "legendFormat": "{{ instance }}" }
     ]
    },
    {
     "title": "Free memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "tasmota_memory_free_bytes", "legendFormat": "{{ instance }}" }
     ]
    }
   ]
  },
  { "title": "WiFi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Signal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "tasmota_wifi_station_signal_dbm",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}