---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "immich.fullname" $ }}-config
  labels:
    {{- include "immich.labels" $ | nindent 4 }}
data:
  immich-config.yaml: |
{{ $.Files.Get "ci/immich-config.yaml" | indent 4 }}
