{{- with .Values.server.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "immich.fullname" $ }}
  labels:
    {{- include "immich.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .type }}
  ports:
    - name: http
      port: {{ .port }}
      targetPort: http
      protocol: TCP
    - name: metrics-api
      port: 8081
      targetPort: metrics-api
      protocol: TCP
    - name: metrics-ms
      port: 8082
      targetPort: metrics-ms
      protocol: TCP
  selector:
    {{- include "immich.selectorLabels" $ | nindent 4 }}
{{- end }}
