{
 "title": "Immich",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(target_info,job)" } },
   {
    "name": "rate",
    "label": "Rate",
    "query": "1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "target_info{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Queue",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "immich_queues_duplicate_detection_active{job=~\"$job\"}",
     "legendFormat": "Duplicate detection"
    },
    {
     "expr": "immich_queues_face_detection_active{job=~\"$job\"}",
     "legendFormat": "Face detection"
    },
    {
     "expr": "immich_queues_metadata_extraction_active{job=~\"$job\"}",
     "legendFormat": "Metadata extraction"
    },
    {
     "expr": "immich_queues_smart_search_active{job=~\"$job\"}",
     "legendFormat": "Smart search"
    },
    {
     "expr": "immich_queues_storage_template_migration_active{job=~\"$job\"}",
     "legendFormat": "Storage migration"
    },
    {
     "expr": "immich_queues_thumbnail_generation_active{job=~\"$job\"}",
     "legendFormat": "Thumbnail generation"
    },
    {
     "expr": "immich_queues_video_conversion_active{job=~\"$job\"}",
     "legendFormat": "Video conversion"
    }
   ]
  },
  {
   "title": "Jobs - skipped",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "immich_jobs_duplicate_detection_skipped_total{job=~\"$job\"}",
     "legendFormat": "Duplicate detection"
    },
    {
     "expr": "immich_jobs_face_detection_skipped_total{job=~\"$job\"}",
     "legendFormat": "Face detection"
    },
    {
     "expr": "immich_jobs_link_live_photos_skipped_total{job=~\"$job\"}",
     "legendFormat": "Link live photos"
    },
    {
     "expr": "immich_jobs_smart_search_skipped_total{job=~\"$job\"}",
     "legendFormat": "Smart search"
    },
    {
     "expr": "immich_jobs_storage_template_migration_single_skipped_total{job=~\"$job\"}",
     "legendFormat": "Storage migration"
    },
    {
     "expr": "immich_jobs_video_conversion_skipped_total{job=~\"$job\"}",
     "legendFormat": "Video conversion"
    }
   ]
  },
  {
   "title": "Jobs - success",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "immich_jobs_generate_preview_success_total{job=~\"$job\"}",
     "legendFormat": "Preview generation "
    },
    {
     "expr": "immich_jobs_generate_thumbhash_success_total{job=~\"$job\"}",
     "legendFormat": "Thumbhash generation"
    },
    {
     "expr": "immich_jobs_generate_thumbnail_success_total{job=~\"$job\"}",
     "legendFormat": "Thumbnail generation"
    },
    {
     "expr": "immich_jobs_smart_search_skipped_total{job=~\"$job\"}",
     "legendFormat": "Smart search"
    },
    {
     "expr": "immich_jobs_metadata_extraction_success_total{job=~\"$job\"}",
     "legendFormat": "Metadata extraction"
    },
    {
     "expr": "immich_jobs_video_conversion_success_total{job=~\"$job\"}",
     "legendFormat": "Video conversion"
    }
   ]
  },
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Duration of inbound HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_bucket{job=\"$job\"}[$rate])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_duration_bucket{job=\"$job\"}[$rate])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_duration_bucket{job=\"$job\"}[$rate])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{job=\"$job\"}[$rate])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_server_duration_bucket{job=\"$job\"}[$rate])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{job=\"$job\"}[$rate])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_server_duration_bucket{job=\"$job\"}[$rate])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Duration of outbound HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_client_duration_bucket{job=\"$job\"}[$rate])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_client_duration_bucket{job=\"$job\"}[$rate])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_client_duration_bucket{job=\"$job\"}[$rate])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_client_duration_bucket{job=\"$job\"}[$rate])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_client_duration_bucket{job=\"$job\"}[$rate])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_client_duration_bucket{job=\"$job\"}[$rate])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_client_duration_bucket{job=\"$job\"}[$rate])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Request method",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (http_method) (increase(http_client_duration_count{job=~\"$job\"}[$rate]))",
     "legendFormat": "{{http_method}}"
    }
   ]
  },
  {
   "title": "Response code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (http_status_code) (increase(http_server_duration_count{job=~\"$job\"}[$rate]))",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  }
 ]
}