---
# Source: immich/templates/server/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: immich
  labels:
    helm.sh/chart: immich-1.0.0
    app.kubernetes.io/name: immich
    app.kubernetes.io/instance: immich
    app.kubernetes.io/version: "v1.113.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: immich
      app.kubernetes.io/instance: immich
  endpoints:
    - port: metrics-api
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
    - port: metrics-ms
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
