---
# Source: argo-cd/charts/argo-cd/templates/argocd-server/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: argo-cd-server
  namespace: argo-cd
  labels:
    helm.sh/chart: argo-cd-7.4.1
    app.kubernetes.io/name: argo-cd-server
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: "v2.12.0"
  annotations:
    datree.skip/SERVICE_INCORRECT_TYPE_VALUE_NODEPORT: "Required for debug purpose"
spec:
  type: NodePort  
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8080
    nodePort: 30443
  selector:
    app.kubernetes.io/name: argo-cd-server
    app.kubernetes.io/instance: argo-cd
