{
 "title": "Argo - Workflows",
 "description": "Metrics from argo-workflows",
 "tags": [ "argo" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(argo_workflows_count,kubernetes_namespace) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Currently",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "WF Pending",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{kubernetes_namespace=~\"$namespace\",status=\"Pending\"} "
    }
   ]
  },
  {
   "title": "WF Running",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{kubernetes_namespace=~\"$namespace\",status=\"Running\"}"
    }
   ]
  },
  {
   "title": "WF Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{kubernetes_namespace=~\"$namespace\",status=\"Error\"}"
    }
   ]
  },
  {
   "title": "WF Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{kubernetes_namespace=~\"$namespace\",status=\"Failed\"}"
    }
   ]
  },
  {
   "title": "WF Skipped",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{kubernetes_namespace=~\"$namespace\",status=\"Skipped\"}"
    }
   ]
  },
  {
   "title": "WF Succeeded",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{kubernetes_namespace=~\"$namespace\",status=\"Succeeded\"}"
    }
   ]
  },
  {
   "title": "Number of Workflows currently accessible by the controller by status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Workflow Status  ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "argo_workflows_count{status!~\"(Error|Failed)\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{status}}"
    }
   ]
  },
  {
   "title": "Workflow Errors Alerting ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "argo_workflows_count{status=~\"(Error|Failed)\"}",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{status}}"
    }
   ]
  },
  {
   "title": "Histogram of durations of operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Workflow operation duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(argo_workflows_operation_duration_seconds_bucket{kubernetes_namespace=~\"^$namespace$\"}[5m])) by (le)) ",
     "legendFormat": "95th percentile"
    }
   ]
  },
  {
   "title": "Adds to the queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Workflow queue adds ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(argo_workflows_queue_adds_count{kubernetes_namespace=~\"$namespace\"}[2m])",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{queue_name}}"
    }
   ]
  },
  {
   "title": "Depth of the queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "argo_workflows_queue_depth_count{kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{queue_name}}"
    }
   ]
  },
  {
   "title": "Time objects spend waiting in the queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "  rate(argo_workflows_queue_latency_sum{queue_name=\"cron_wf_queue\",kubernetes_namespace=~\"^$namespace$\"}[5m])\n/\n  rate(argo_workflows_queue_latency_count{queue_name=\"cron_wf_queue\",kubernetes_namespace=~\"^$namespace$\"}[5m])",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{queue_name}}"
    },
    {
     "expr": "  rate(argo_workflows_queue_latency_sum{queue_name=\"pod_queue\",kubernetes_namespace=~\"^$namespace$\"}[5m])\n/\n  rate(argo_workflows_queue_latency_count{queue_name=\"pod_queue\",kubernetes_namespace=~\"^$namespace$\"}[5m])",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{queue_name}}"
    },
    {
     "expr": "  rate(argo_workflows_queue_latency_sum{queue_name=\"wf_cron_queue\",kubernetes_namespace=~\"^$namespace$\"}[5m])\n/\n  rate(argo_workflows_queue_latency_count{queue_name=\"wf_cron_queue\",kubernetes_namespace=~\"^$namespace$\"}[5m])",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{queue_name}}"
    },
    {
     "expr": "  rate(argo_workflows_queue_latency_sum{queue_name=\"workflow_queue\",kubernetes_namespace=~\"^$namespace$\"}[5m])\n/\n  rate(argo_workflows_queue_latency_count{queue_name=\"workflow_queue\",kubernetes_namespace=~\"^$namespace$\"}[5m])",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{queue_name}}"
    }
   ]
  },
  {
   "title": "Total number of log messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Log messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(log_messages{kubernetes_namespace=~\"$namespace\"}[2m])",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{level}}"
    }
   ]
  }
 ]
}