{
 "title": "eBPF",
 "description": "Metrics from ebpf-exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Node",
    "query": {
     "query": "label_values(ebpf_exporter_build_info,hostname)"
    }
   },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(ebpf_exporter_bio_latency_seconds_sum{hostname=~\"$hostname\"}, device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "eBpf Enable Config", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ebpf enable ${hostname}",
   "type": "status-history",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "repeat": "hostname",
   "targets": [
    {
     "expr": "ebpf_exporter_enabled_configs{hostname=~\"$hostname\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "BIO Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "biolatency read",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bio_latency_seconds_bucket{operation=\"read\", hostname=~\"$hostname\", device=~\"$device\"}[5m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "biolatency write",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bio_latency_seconds_bucket{operation=\"write\", hostname=~\"$hostname\", device=~\"$device\"}[5m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "biolatency flush",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bio_latency_seconds_bucket{operation=\"flush\", hostname=~\"$hostname\", device=~\"$device\"}[5m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Percentiles and averages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(ebpf_exporter_bio_latency_seconds_bucket{hostname=~\"$hostname\", device=~\"$device\"}[$__rate_interval]) )",
     "legendFormat": "90% {{operation}} {{device}}"
    },
    {
     "expr": "histogram_quantile(0.95, rate(ebpf_exporter_bio_latency_seconds_bucket{hostname=~\"$hostname\", device=~\"$device\"}[$__rate_interval]) )",
     "legendFormat": "95% {{operation}} {{device}}"
    },
    {
     "expr": "rate(ebpf_exporter_bio_latency_seconds_sum{hostname=~\"$hostname\", device=~\"$device\"}[$__rate_interval]) / rate(ebpf_exporter_bio_latency_seconds_count{hostname=~\"$hostname\", device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "{{operation}} {{device}} average"
    }
   ]
  },
  {
   "title": "Accept Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Accept Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_accept_latency_seconds_sum{hostname=~\"$hostname\"}[$__rate_interval]) or rate(ebpf_exporter_accept_latency_seconds_count{hostname=~\"$hostname\"}[5m])",
     "legendFormat": "avg {{hostname}} {{port}}"
    }
   ]
  },
  {
   "title": "90% Percentiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(ebpf_exporter_accept_latency_seconds_bucket{hostname=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "90% accept {{hostname}} {{port}}"
    }
   ]
  },
  {
   "title": "99% Percentiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(ebpf_exporter_accept_latency_seconds_bucket{hostname=~\"$hostname\"}[$__rate_interval]) )",
     "legendFormat": "95% accept {{hostname}} {{port}}"
    }
   ]
  },
  {
   "title": "Averages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(ebpf_exporter_accept_latency_seconds_sum{hostname=~\"$hostname\"}[$__rate_interval]) / rate(ebpf_exporter_accept_latency_seconds_count{hostname=~\"$hostname\"}[$__rate_interval])",
     "legendFormat": "avg accept {{hostname}} {{port}}"
    }
   ]
  },
  { "title": "JIT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "JIT pages allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bpf_jit_pages_currently_allocated{ hostname=~\"$hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Cgroup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Cgroup Sched Migrations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_cgroup_sched_migrations_total{ hostname=~\"$hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Program", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "eBPF Program",
   "type": "status-history",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "sum by (program) (ebpf_exporter_ebpf_program_info{hostname=~\"$hostname\"})",
     "legendFormat": "{{program}}"
    }
   ]
  },
  {
   "title": "eBPF Program Attached",
   "type": "status-history",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "sum by (id) (ebpf_exporter_ebpf_program_attached{hostname=~\"$hostname\"})",
     "legendFormat": "pid {{id}}"
    }
   ]
  },
  { "title": "PageCache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Page Cache OPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum by (hostname, op) (\n  rate(ebpf_exporter_page_cache_ops_total{ hostname=~\"$hostname\"}[$__rate_interval])\n)",
     "legendFormat": "{{hostname}} {{op}}"
    }
   ]
  },
  { "title": "Timer Starts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "Raw timer Starts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (hostname, function) (rate(ebpf_exporter_raw_timer_starts_total{ hostname=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "{{hostname}} {{function}}"
    }
   ]
  },
  {
   "title": "Timer Starts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (hostname, function) (rate(ebpf_exporter_timer_starts_total{ hostname=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "{{hostname}} {{function}}"
    }
   ]
  },
  { "title": "ShrinkNodeLatencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "90% Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(ebpf_exporter_shrink_node_latency_seconds_bucket{hostname=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "90% {{hostname}}  "
    }
   ]
  },
  {
   "title": "95% Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(ebpf_exporter_shrink_node_latency_seconds_bucket{hostname=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "95% {{hostname}} "
    }
   ]
  },
  {
   "title": "Accept Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_shrink_node_latency_seconds_sum{hostname=~\"$hostname\"}[$__rate_interval]) or rate(ebpf_exporter_shrink_node_latency_seconds_count{hostname=~\"$hostname\"}[5m])",
     "legendFormat": "avg {{hostname}} "
    }
   ]
  },
  { "title": "TcpSynBacklog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 } },
  {
   "title": "90% Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(ebpf_exporter_tcp_syn_backlog_bucket{hostname=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "90% {{hostname}} "
    }
   ]
  },
  {
   "title": "95% Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(ebpf_exporter_tcp_syn_backlog_bucket{hostname=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "95% {{hostname}} "
    }
   ]
  },
  {
   "title": "Accept Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_tcp_syn_backlog_sum{hostname=~\"$hostname\"}[$__rate_interval]) or rate(ebpf_exporter_tcp_syn_backlog_count{hostname=~\"$hostname\"}[5m])",
     "legendFormat": "avg {{hostname}} "
    }
   ]
  },
  { "title": "TcpWindowClamps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 } },
  {
   "title": "TCP Window Clamps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (hostname) (rate(ebpf_exporter_tcp_window_clamps_total{ hostname=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}