---
# Source: immich/charts/valkey/templates/master/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: immich-valkey-master
  namespace: "immich"
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: valkey
    app.kubernetes.io/version: 7.2.6
    helm.sh/chart: valkey-0.3.15
    app.kubernetes.io/part-of: valkey
