{
 "title": "Blocky",
 "description": "Blocky - Metrics",
 "tags": [ "blocky" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(blocky_build_info, instance)"
    }
   },
   { "name": "blocky_url", "label": "Blocky URL", "query": "http://3.124.214.158:32286" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running",
   "type": "stat",
   "description": "Current running status",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"blocky-http\"})"
    }
   ]
  },
  {
   "title": "Blocking",
   "type": "stat",
   "description": "Is blocking enabled?",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blocky_blocking_enabled{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Time since last list refresh",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - blocky_last_list_group_refresh{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Domains on Blacklist",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blocky_blacklist_cache{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total queries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blocky_query_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Blocked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blocky_response_total{instance=~\"$instance\", response_type=\"BLOCKED\"}"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (client) (blocky_query_total{instance=~\"$instance\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache entries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "blocky_cache_entry_count{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Enable/Disable blocking",
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": {
    "content": "<style>\n\n.blocky_btn {\n    border: none;\n  cursor: pointer; \n    padding: 12px;\n  font-size: 16px;\n  min-width: 100px\n}\n\n.blocky_greenbtn { \n  background-color: #4CAF50;\n  color: white;\n}\n\n.blocky_redbtn { \n  background-color: #AF504C;\n  color: white;\n}\n\n\n.blocky_alert {\n  font-size: 14px\n}\n</style>\n\n<div class=\"blocky_alert blocky_alert-warning fade in\">\n    <a href=\"#\" class=\"close\" data-dismiss=\"blocky_alert\" aria-label=\"close\" style=\"text-decoration:none\">&times;</a>Done!\n</div>\n<div>\n    <button class=\"blocky_btn blocky_greenbtn\" onclick=\"blocky_status_enable()\">On</button>\n    <button class=\"blocky_btn blocky_redbtn\" onclick=\"blocky_status_disable()\">Off</button>\n    <button class=\"blocky_btn blocky_redbtn\" onclick=\"blocky_status_disable5m()\">Off 5m</button>\n    <button class=\"blocky_btn blocky_redbtn\" onclick=\"blocky_status_disable30m()\">Off 30m</button>\n<div>\n\n<script type=\"text/javascript\">\n\nfunction blocky_status_disable() {\n     blocky_status_switch(false, 0)\n}\n\nfunction blocky_status_disable5m() {\n    blocky_status_switch(false, 5*60)\n}\n\nfunction blocky_status_disable30m() {\n    blocky_status_switch(false, 30*60)\n}\n\nfunction blocky_status_enable() {\n    blocky_status_switch(true, 0)\n}\n\nfunction blocky_status_switch(enable, duration) {\n    op = enable ? 'enable' : 'disable?duration=' + duration + \"s\"\n    var url = '$blocky_url' + '/api/blocking/' + op;\n    $.get(url, function(data) {\n        showAlert()\n    })\n    .fail(function(obj, textStatus, error) {\n        alert(\"URL: \" + url + \"\\n\" + \"error: \" + error);\n    })\n}\n\nvar showAlert = function() {\n    // first show the alert\n    $('.blocky_alert').show().fadeTo(500, 1);\n  \n    // Now set a timeout to hide it\n    window.setTimeout(function() {\n        $(\".blocky_alert\").fadeTo(500, 0).slideUp(500, function() {\n        $(this).hide();\n        });\n    }, 3000);\n}\n\n// start with the alert hidden\n$('.blocky_alert').hide();\n\n</script>\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Error count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blocky_error_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Prefetch count",
   "type": "stat",
   "description": "Amount of performed DNS queries to prefetch cached queries",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blocky_prefetch_count{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Prefetch domain count",
   "type": "stat",
   "description": "Amount of unique domains in the prefetched cache",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blocky_prefetch_domain_name_cache_count{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Prefetch rate per min",
   "type": "stat",
   "description": "Amount of prefetch queries per minute",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(blocky_prefetch_count{instance=~\"$instance\"}[5m])) * 60"
    }
   ]
  },
  {
   "title": "Prefetch Hit ratio",
   "type": "stat",
   "description": "How many of cached entries were prefetched automatically",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "blocky_prefetch_hit_count{instance=~\"$instance\"} / blocky_cache_hit_count{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Cache Hit/Miss ratio",
   "type": "stat",
   "description": "Cache Hit/Miss ratio. 100 % means, all queries could be answered from the cache, 0% - all queries must be resolved via external DNS",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "blocky_cache_hit_count{instance=~\"$instance\"} / (blocky_cache_hit_count{instance=~\"$instance\"} + blocky_cache_miss_count{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Memory allocated",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "GO Routine",
   "type": "stat",
   "description": "Number of goroutines that currently exist",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "GO Threads",
   "type": "stat",
   "description": "Number of threads that currently exist",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_threads{instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Response", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "description": "Average query response time for all query types",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(blocky_request_duration_ms_sum{instance=~\"$instance\"}[1m]) / rate(blocky_request_duration_ms_count{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{ response_type }}"
    }
   ]
  },
  { "title": "Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(blocky_query_total{instance=~\"$instance\"}[1m]) * 60",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Request rate per client",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (client) (rate(blocky_query_total{instance=~\"$instance\"}[1m])) * 60",
     "legendFormat": " {{client}}"
    }
   ]
  },
  {
   "title": "Request duration (upstream)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(blocky_request_duration_ms_bucket{response_type=\"RESOLVED\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Pie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Query by type",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (type) (ceil(increase(blocky_query_total{instance=~\"$instance\"}[$__range]))))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Query per Client",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 9, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (client) (ceil(increase(blocky_query_total{instance=~\"$instance\"}[$__range]))))",
     "legendFormat": "{{ client }}"
    }
   ]
  },
  {
   "title": "Blacklist by group",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 7, "x": 15, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, blocky_blacklist_cache{instance=~\"$instance\"}) by (group)",
     "legendFormat": "{{ group }}"
    }
   ]
  },
  {
   "title": "Response Reasons",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 1, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (reason) (ceil(increase(blocky_response_total{instance=~\"$instance\"}[$__range]))))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Response status",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 8, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (response_code) (ceil(increase(blocky_response_total{instance=~\"$instance\"}[$__range]))))",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "Response Type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 15, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (response_type) (ceil(increase(blocky_response_total{instance=~\"$instance\"}[$__range]))))",
     "legendFormat": "{{response_type}}"
    }
   ]
  }
 ]
}