{
 "title": "Blocky - Query Log",
 "description": "Blocky - QueryLog Metrics",
 "tags": [
  "blocky",
  "loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (client_names, client_ip) (\n    count_over_time(\n        {app=\"blocky\"} | json | prefix = `queryLog` [$__range]\n    )\n)",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Domains",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum by (domain) (\n    count_over_time(\n        {app=\"blocky\"} | regexp `\"question\":\"(?P<request_type>\\S+)\\s+\\((?P<domain>\\S+)\\)` | json | prefix = `queryLog` [$__range]\n    )\n)",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"blocky\"} | regexp `\"response_reason\":\".*\\s+\\((?P<upstream>\\S+)\\)` | json | prefix = `queryLog`"
    }
   ]
  }
 ]
}