{
 "title": "Cilium - Hubble",
 "tags": [ "cilium" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "General Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Flows processed Per Node",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(sum(rate(hubble_flows_processed_total[$__rate_interval])) by (pod))",
     "legendFormat": "avg"
    },
    {
     "expr": "min(sum(rate(hubble_flows_processed_total[$__rate_interval])) by (pod))",
     "legendFormat": "min"
    },
    {
     "expr": "max(sum(rate(hubble_flows_processed_total[$__rate_interval])) by (pod))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Flows Types",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total[$__rate_interval])) by (pod, type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "L7 Flow Distribution",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total{type=\"L7\"}[$__rate_interval])) by (pod, subtype)",
     "legendFormat": "{{subtype}}"
    }
   ]
  },
  {
   "title": "Trace Flow Distribution",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total{type=\"Trace\"}[$__rate_interval])) by (pod, subtype)",
     "legendFormat": "{{subtype}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Forwarded vs Dropped",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(hubble_flows_processed_total[$__rate_interval])) by (pod, verdict)",
       "legendFormat": "{{verdict}}"
      }
     ]
    },
    {
     "title": "Drop Reason",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(hubble_drop_total[$__rate_interval])) by (pod, reason)",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Protocol Usage",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum (rate(hubble_port_distribution_total[$__rate_interval])) by (pod, protocol)",
       "legendFormat": "{{protocol}}"
      }
     ]
    },
    {
     "title": "Top 10 Port Distribution",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "topk(10, sum (rate(hubble_port_distribution_total{port!=\"0\"}[$__rate_interval])) by (pod, port, protocol))",
       "legendFormat": "{{port}}/{{protocol}}"
      }
     ]
    },
    {
     "title": "TCPv4",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(hubble_tcp_flags_total{family=\"IPv4\"}[$__rate_interval])) by (pod, flag)",
       "legendFormat": "{{flag}}"
      }
     ]
    },
    {
     "title": "Missing TCPv4 SYN-ACKs",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(hubble_tcp_flags_total{family=\"IPv4\", flag=\"SYN\"}[$__rate_interval])) by (pod) - sum(rate(hubble_tcp_flags_total{family=\"IPv4\", flag=\"SYN-ACK\"}[$__rate_interval])) by (pod)",
       "legendFormat": "Missing SYN-ACK"
      }
     ]
    },
    {
     "title": "TCPv6",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(hubble_tcp_flags_total{family=\"IPv6\"}[$__rate_interval])) by (pod, flag)",
       "legendFormat": "{{flag}}"
      }
     ]
    },
    {
     "title": "Missing TCPv6 SYN-ACKs",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(hubble_tcp_flags_total{family=\"IPv6\", flag=\"SYN\"}[$__rate_interval])) by (pod) - sum(rate(hubble_tcp_flags_total{family=\"IPv6\", flag=\"SYN-ACK\"}[$__rate_interval])) by (pod)",
       "legendFormat": "Missing SYN-ACK"
      }
     ]
    },
    {
     "title": "ICMPv4",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(hubble_icmp_total{family=\"IPv4\"}[$__rate_interval])) by (pod, type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Missing ICMPv4 Echo-Reply",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(hubble_icmp_total{family=\"IPv4\", type=\"EchoRequest\"}[$__rate_interval])) by (pod) - sum(rate(hubble_icmp_total{family=\"IPv4\", type=\"EchoReply\"}[$__rate_interval])) by (pod)",
       "legendFormat": "Missing ICMP Echo-Reply"
      }
     ]
    },
    {
     "title": "ICMPv6",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(hubble_icmp_total{family=\"IPv6\"}[$__rate_interval])) by (pod, type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Missing ICMPv6 Echo-Reply",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(hubble_icmp_total{family=\"IPv6\", type=\"EchoRequest\"}[$__rate_interval])) by (pod) - sum(rate(hubble_icmp_total{family=\"IPv6\", type=\"EchoReply\"}[$__rate_interval])) by (pod)",
       "legendFormat": "Missing ICMP Echo-Reply"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Policy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Denies by Reason",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(hubble_drop_total{reason=\"POLICY_DENIED\"}[$__rate_interval])) by (pod, reason)",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Denied Packets by Protocol",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(hubble_drop_total{reason=\"POLICY_DENIED\"}[$__rate_interval])) by (pod, protocol)",
       "legendFormat": "{{protocol}}"
      }
     ]
    },
    {
     "title": "Top 10 Source Pods with Denied Packets",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "topk(10, sum(rate(hubble_drop_total{reason=\"POLICY_DENIED\"}[$__rate_interval])) by (pod, source))",
       "legendFormat": "{{source}}"
      }
     ]
    },
    {
     "title": "Top 10 Destination Pods with Denied Packets",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "topk(10, sum(rate(hubble_drop_total{reason=\"POLICY_DENIED\"}[$__rate_interval])) by (pod, destination))",
       "legendFormat": "{{destination}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "HTTP Requests",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(hubble_http_requests_total[$__rate_interval])) by (pod, method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "HTTP Protocol Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(hubble_http_requests_total[5m])) by (pod, protocol)",
       "legendFormat": "{{protocol}}"
      }
     ]
    },
    {
     "title": "HTTP Request/Response Latency (p50)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(hubble_http_request_duration_seconds_bucket[$__rate_interval]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "HTTP Request/Response Latency (p99)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(hubble_http_request_duration_seconds_bucket[$__rate_interval]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "HTTP responses",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(hubble_http_responses_total[$__rate_interval])) by (pod, status)",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DNS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DNS Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_dns_queries_total[$__rate_interval])) by (pod, qtypes)",
     "legendFormat": "{{qtypes}}"
    }
   ]
  },
  {
   "title": "DNS responses",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_dns_responses_total{rcode=\"No Error\"}[$__rate_interval])) by (pod, qtypes)",
     "legendFormat": "{{qtypes}}"
    }
   ]
  },
  {
   "title": "Missing DNS Responses",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_dns_queries_total[$__rate_interval])) by (pod, qtypes) - sum(rate(hubble_dns_responses_total[$__rate_interval])) by (pod, qtypes)",
     "legendFormat": "{{qtypes}}"
    }
   ]
  },
  {
   "title": "DNS Response Record Type",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_dns_response_types_total[$__rate_interval])) by (pod, type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "DNS Response IPs Returned",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_dns_responses_total{rcode=\"No Error\"}[$__rate_interval])) by (pod,ips_returned)",
     "legendFormat": "{{ips_returned}}"
    }
   ]
  },
  {
   "title": "DNS Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_dns_responses_total{rcode!=\"No Error\"}[$__rate_interval])) by (pod, qtypes, rcode)",
     "legendFormat": "{{rcode}} ({{qtypes}})"
    }
   ]
  },
  {
   "title": "Pods with DNS errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,sum(rate(hubble_dns_responses_total{rcode!=\"No Error\"}[$__rate_interval])) by (pod, destination))",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  {
   "title": "Top 10 DNS Queries per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(hubble_dns_queries_total[10m])*60) by (query, qtypes))",
     "legendFormat": "{{query}} ({{qtypes}})"
    }
   ]
  }
 ]
}