##################################
#         Global settings        #
##################################
# List of local addresses and ports to listen to.
listen_addresses = ['0.0.0.0:5053']

# Maximum number of simultaneous client connections to accept
max_clients = 250

# Use servers reachable over IPv4
ipv4_servers = true

# Use servers reachable over IPv6 -- Do not enable if you don't have IPv6 connectivity
ipv6_servers = false

# Use servers implementing the DNSCrypt protocol
dnscrypt_servers = true

# Use servers implementing the DNS-over-HTTPS protocol
doh_servers = true

# Server must support DNS security extensions (DNSSEC)
require_dnssec = true

# Server must not log user queries (declarative)
require_nolog = true

# Server must not enforce its own blacklist (for parental control, ads blocking...)
require_nofilter = true

# Server names to avoid even if they match all criteria
disabled_server_names = []

# Always use TCP to connect to upstream servers (useful if you need to route everything through Tor).
force_tcp = false

## How long a DNS query will wait for a response, in milliseconds.
timeout = 5000

# Keepalive for HTTP (HTTPS, HTTP/2) queries, in seconds
keepalive = 30

# Delay, in minutes, after which certificates are reloaded
cert_refresh_delay = 240

# Fallback resolvers
## These are normal, non-encrypted DNS resolvers, that will be only used
## for one-shot queries when retrieving the initial resolvers list, and
## only if the system DNS configuration doesn't work.
## No user application queries will ever be leaked through these resolvers,
## and they will not be used after IP addresses of resolvers URLs have been found.
## They will never be used if lists have already been cached, and if stamps
## don't include host names without IP addresses.
## They will not be used if the configured system DNS works.
## Resolvers supporting DNSSEC are recommended.
bootstrap_resolvers = ['9.9.9.9:53', '8.8.8.8:53']

# Always use the fallback resolver before the system DNS settings.
ignore_system_dns = true

# Maximum time (in seconds) to wait for network connectivity before initializing the proxy.
netprobe_timeout = 60

## Address and port to try initializing a connection to, just to check
## if the network is up. It can be any address and any port, even if
## there is nothing answering these on the other side. Just don't use
## a local address, as the goal is to check for Internet connectivity.
## On Windows, a datagram with a single, nul byte will be sent, only
## when the system starts.
## On other operating systems, the connection will be initialized
## but nothing will be sent at all.
netprobe_address = '9.9.9.9:53'

# Automatic log files rotation
## Maximum log files size in MB - Set to 0 for unlimited.
log_files_max_size = 10

## How long to keep backup files, in days
log_files_max_age = 7

## Maximum log files backups to keep (or 0 to keep all backups)
log_files_max_backups = 1


#########################
#        Filters        #
#########################
# Immediately respond to IPv6-related queries with an empty response
## This makes things faster when there is no IPv6 connectivity, but can
## also cause reliability issues with some stub resolvers.
block_ipv6 = true

# Immediately respond to A and AAAA queries for host names without a domain name
block_unqualified = true

# Immediately respond to queries for local zones instead of leaking them to
## upstream resolvers (always causing errors or timeouts).
block_undelegated = true

## TTL for synthetic responses sent when a request has been blocked (due to IPv6 or blacklists).
reject_ttl = 600


###########################
#        DNS cache        #
###########################
# Enable a DNS cache to reduce latency and outgoing traffic
cache = true

# Cache size
cache_size = 4096

# Minimum TTL for cached entries
cache_min_ttl = 2400

# Maximum TTL for cached entries
cache_max_ttl = 86400

# Minimum TTL for negatively cached entries
cache_neg_min_ttl = 60

# Maximum TTL for negatively cached entries
cache_neg_max_ttl = 600


#########################
#        Servers        #
#########################
# Remote lists of available servers
[sources]

  # An example of a remote source from https://github.com/DNSCrypt/dnscrypt-resolvers
  [sources.'public-resolvers']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md', 'https://ipv6.download.dnscrypt.info/resolvers-list/v3/public-resolvers.md', 'https://download.dnscrypt.net/resolvers-list/v3/public-resolvers.md']
  cache_file = 'public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'  # pragma: allowlist secret
  refresh_delay = 72
  prefix = ''

  # Anonymized DNS relays
  [sources.'relays']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/relays.md', 'https://download.dnscrypt.info/resolvers-list/v3/relays.md', 'https://ipv6.download.dnscrypt.info/resolvers-list/v3/relays.md', 'https://download.dnscrypt.net/resolvers-list/v3/relays.md']
  cache_file = 'relays.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'  # pragma: allowlist secret
  refresh_delay = 72
  prefix = ''


#########################################
#        Servers with known bugs        #
#########################################
[broken_implementations]
# Cisco servers currently cannot handle queries larger than 1472 bytes, and don't
# truncate responses larger than questions as expected by the DNSCrypt protocol.
# This prevents large responses from being received over UDP and over relays.
#
# The `dnsdist` server software drops client queries larger than 1500 bytes.
# They are aware of it and are working on a fix.
#
# The list below enables workarounds to make non-relayed usage more reliable
# until the servers are fixed.
  fragments_blocked = ['cisco', 'cisco-ipv6', 'cisco-familyshield', 'cisco-familyshield-ipv6', 'cleanbrowsing-adult', 'cleanbrowsing-adult-ipv6', 'cleanbrowsing-family', 'cleanbrowsing-family-ipv6', 'cleanbrowsing-security', 'cleanbrowsing-security-ipv6']
