---
annotations:
  datree.skip/CONTAINERS_INCORRECT_PRIVILEGED_VALUE_TRUE: Required for GPU transcoding
  ignore-check.kube-linter.io/privileged-container: Required to write transcoding
  ignore-check.kube-linter.io/privilege-escalation-container: Required to write transcoding
  ignore-check.kube-linter.io/no-read-only-root-fs: Required to write transcoding
  ignore-check.kube-linter.io/writable-host-mount: Required to write config

# GPU transcoding
securityContext:
  # Required for GPU transcoding
  privileged: true
  allowPrivilegeEscalation: true
  # Required to write transcoding
  readOnlyRootFilesystem: false
extraVolumes:
  - name: dri
    hostPath:
      path: /dev/dri
extraVolumeMounts:
  - name: dri
    mountPath: /dev/dri

ingress:
  enabled: true
  ingressClassName: cilium
  annotations:
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: jellyfin.mukka.haus
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: jellyfin-tls
      hosts:
        - jellyfin.mukka.haus

persistence:
  config:
    enabled: true
    storageClassName: jellyfin-config
    size: 1Gi
  media:
    enabled: true
    storageClassName: jellyfin-media
    size: 100Gi

extraManifests:
  - apiVersion: cilium.io/v2
    kind: CiliumNetworkPolicy
    metadata:
      name: restrict
    spec:
      # Apply to all pods in namespacee
      endpointSelector: {}
      # Allow ingress from anywhere
      egress:
        # Allow to resolve DNS
        - toEndpoints:
            - matchLabels:
                io.kubernetes.pod.namespace: kube-system
                k8s-app: kube-dns
          toPorts:
            - ports:
                - port: "53"
                  protocol: UDP
              rules:
                dns:
                  - matchPattern: "*"
        # Allow egress only to https://
        - toFQDNs:
            # Plugins
            - matchName: repo.jellyfin.org
            - matchName: fra1.mirror.jellyfin.org
            - matchName: raw.githubusercontent.com
            # Subtitles
            - matchName: api.opensubtitles.com
            # Movie metadata
            - matchName: www.omdbapi.com
            - matchName: api.themoviedb.org
            - matchName: image.tmdb.org
          toPorts:
            - ports:
                - port: "443"
        # Allow to run tests (egress to all pods in namespace)
        - toEndpoints:
            - {}

  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: jellyfin-config
    provisioner: kubernetes.io/no-provisioner
    volumeBindingMode: WaitForFirstConsumer

  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: jellyfin-config
      labels:
        type: local
    spec:
      storageClassName: jellyfin-config
      capacity:
        storage: 1Gi
      accessModes:
        - ReadWriteOnce
      local:
        path: /data/jellyfin-config
      nodeAffinity:
        required:
          nodeSelectorTerms:
            - matchExpressions:
                - key: disk
                  operator: In
                  values:
                    - local

  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: jellyfin-media
    provisioner: kubernetes.io/no-provisioner
    volumeBindingMode: WaitForFirstConsumer

  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: jellyfin-media
      labels:
        type: local
    spec:
      storageClassName: jellyfin-media
      capacity:
        storage: 100Gi
      accessModes:
        - ReadWriteOnce
      local:
        path: /data/jellyfin-media
      nodeAffinity:
        required:
          nodeSelectorTerms:
            - matchExpressions:
                - key: disk
                  operator: In
                  values:
                    - local
