---
apiVersion: v2
name: monitoring-subchart
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: sealed-secrets
    version: 2.7.2
    repository: https://bitnami-labs.github.io/sealed-secrets
  - name: kube-prometheus-stack
    version: 43.2.1
    repository: https://prometheus-community.github.io/helm-charts
