---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "tailscale.fullname" . }}
rules:
  # Create can not be restricted to a resource name.
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      - create
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - {{ .Values.stateSecretName | quote }}
    # kics-scan ignore-line
    verbs:
      - get
      - update
      - patch
