{
 "title": "Pi-Hole - Logs",
 "description": "Metrics from Pi-Hole using https://gitlab.com/yellowhat-labs/pihole2influxdb",
 "tags": [ "pihole" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "bucket", "query": "buckets()" },
   {
    "name": "measurement",
    "query": "import \"influxdata/influxdb/v1\"\nv1.measurements(bucket: \"${bucket}\")"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"summary\" and r._field == \"status\")"
    }
   ]
  },
  {
   "title": "Domains on Adlists",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"summary\" and r._field == \"domains_being_blocked\")"
    }
   ]
  },
  {
   "title": "Time since Gravity updated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "currentSeconds = (int(v: now()) / 1000000000)\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"summary\" and r._field == \"gravity_last_updated\")\n  |> last()\n  |> map(fn: (r) => ({r with _value: currentSeconds - int(v: r._value)}))"
    }
   ]
  },
  {
   "title": "Total Queries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\")\r\n  |> group(columns: [\"_start\"])\r\n  |> count()\r\n"
    }
   ]
  },
  {
   "title": "Total BLOCKED",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.status == \"BLOCKED\")\r\n  |> group(columns: [\"_start\"])\r\n  |> count()\r\n"
    }
   ]
  },
  {
   "title": "Total Clients (interval)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\")\r\n  |> group(columns: [\"client\"])\r\n  |> count()\r\n  |> group()\r\n  |> count()"
    }
   ]
  },
  {
   "title": "Total Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(bucket: \"${bucket}\", tag: \"client\")\r\n  |> count()"
    }
   ]
  },
  {
   "title": "Clients - all",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\")\n  |> group(columns: [\"client\"])\n  |> count()\n  |> group()\n"
    }
   ]
  },
  {
   "title": "Clients - BLOCKED",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.status == \"BLOCKED\")\n  |> group(columns: [\"client\"])\n  |> count()\n  |> group()\n"
    }
   ]
  },
  {
   "title": "Top Domains - all",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\")\n  |> group(columns: [\"domain\"])\n  |> count()\n  |> group()\n"
    }
   ]
  },
  {
   "title": "Top Domains - BLOCKED",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.status == \"BLOCKED\")\n  |> group(columns: [\"domain\"])\n  |> count()\n  |> group()\n"
    }
   ]
  },
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Activity - 5 min window - per client",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\")\n  |> group(columns: [\"client\"])\n  |> aggregateWindow(every: 5m, fn: count)"
    }
   ]
  },
  {
   "title": "Activity - 5 min window - per status",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\")\n  |> group(columns: [\"status\"])\n  |> aggregateWindow(every: 5m, fn: count)"
    }
   ]
  },
  { "title": "Pie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Status",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\")\n  |> group(columns: [\"status\"])\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Reply Type",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\")\n  |> group(columns: [\"reply_type\"])\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Query Type",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\")\n  |> group(columns: [\"query_type\"])\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Upstream",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\")\n  |> group(columns: [\"upstream\"])\n  |> count()\n"
    }
   ]
  },
  { "title": "Reply time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Reply time",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r._field == \"reply_time_ms\")\n  |> group(columns: [\"client\"])\n  |> drop(columns: [\"_start\", \"_stop\"])"
    }
   ]
  },
  {
   "title": "Reply time - 5 min window",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r._field == \"reply_time_ms\")\n  |> group(columns: [\"client\"])\n  |> aggregateWindow(every: 5m, fn: mean)\n  |> set(key: \"client\", value: \"mean\")"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r._field == \"reply_time_ms\")\n  |> group(columns: [\"client\"])\n  |> aggregateWindow(every: 5m, fn: median)\n    |> set(key: \"client\", value: \"median\")"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r._field == \"reply_time_ms\")\n  |> group(columns: [\"client\"])\n    |> aggregateWindow(\n        every: 5m,\n        fn: (tables=<-, column) => tables\n            |> quantile(q: 0.9, method: \"exact_selector\"),\n    )\n    |> set(key: \"client\", value: \"quantile 90%\")"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r._field == \"reply_time_ms\")\n  |> group(columns: [\"client\"])\n    |> aggregateWindow(\n        every: 5m,\n        fn: (tables=<-, column) => tables\n            |> quantile(q: 0.95, method: \"exact_selector\"),\n    )\n    |> set(key: \"client\", value: \"quantile 95%\")"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r._field == \"reply_time_ms\")\n  |> group(columns: [\"client\"])\n    |> aggregateWindow(\n        every: 5m,\n        fn: (tables=<-, column) => tables\n            |> quantile(q: 0.99, method: \"exact_selector\"),\n    )\n    |> set(key: \"client\", value: \"quantile 99%\")"
    }
   ]
  }
 ]
}