{
 "title": "Pi-Hole - Logs (Filter)",
 "description": "Metrics from Pi-Hole using https://gitlab.com/yellowhat-labs/pihole2influxdb - by client",
 "tags": [ "pihole" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "bucket", "query": "buckets()" },
   {
    "name": "measurement",
    "query": "import \"influxdata/influxdb/v1\"\nv1.measurements(bucket: \"${bucket}\")"
   },
   {
    "name": "client",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"${bucket}\", tag: \"client\")"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.client =~ /^${client:regex}$/)\r\n  |> group(columns: [\"_start\"])\r\n  |> count()\r\n"
    }
   ]
  },
  {
   "title": "Total BLOCKED",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.client =~ /^${client:regex}$/ and r.status == \"BLOCKED\")\r\n  |> group(columns: [\"_start\"])\r\n  |> count()\r\n"
    }
   ]
  },
  {
   "title": "Clients - all",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.client =~ /^${client:regex}$/)\n  |> group(columns: [\"client\"])\n  |> count()\n  |> group()\n"
    }
   ]
  },
  {
   "title": "Clients - BLOCKED",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.client =~ /^${client:regex}$/ and r.status == \"BLOCKED\")\n  |> group(columns: [\"client\"])\n  |> count()\n  |> group()\n"
    }
   ]
  },
  {
   "title": "Top Domains - all",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.client =~ /^${client:regex}$/)\n  |> group(columns: [\"domain\"])\n  |> count()\n  |> group()\n"
    }
   ]
  },
  {
   "title": "Top Domains - BLOCKED",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.client =~ /^${client:regex}$/ and r.status == \"BLOCKED\")\n  |> group(columns: [\"domain\"])\n  |> count()\n  |> group()\n"
    }
   ]
  },
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Activity - 5 min window - per client",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.client =~ /^${client:regex}$/)\n  |> group(columns: [\"client\"])\n  |> aggregateWindow(every: 5m, fn: count)"
    }
   ]
  },
  {
   "title": "Activity - 5 min window - per status",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.client =~ /^${client:regex}$/)\n  |> group(columns: [\"status\"])\n  |> aggregateWindow(every: 5m, fn: count)"
    }
   ]
  },
  { "title": "Pie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Status",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.client =~ /^${client:regex}$/)\n  |> group(columns: [\"status\"])\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Reply Type",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.client =~ /^${client:regex}$/)\n  |> group(columns: [\"reply_type\"])\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Query Type",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.client =~ /^${client:regex}$/)\n  |> group(columns: [\"query_type\"])\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Upstream",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.client =~ /^${client:regex}$/)\n  |> group(columns: [\"upstream\"])\n  |> count()\n"
    }
   ]
  },
  { "title": "Reply time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.client =~ /^${client:regex}$/)\n  |> group()"
    }
   ]
  },
  {
   "title": "Reply time",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.client =~ /^${client:regex}$/ and r._field == \"reply_time_ms\")\n  |> group(columns: [\"client\"])\n  |> drop(columns: [\"_start\", \"_stop\"])"
    }
   ]
  },
  {
   "title": "Reply time - 5 min window",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.client =~ /^${client:regex}$/ and r._field == \"reply_time_ms\")\n  |> group(columns: [\"client\"])\n  |> aggregateWindow(every: 5m, fn: mean)\n  |> set(key: \"client\", value: \"mean\")"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.client =~ /^${client:regex}$/ and r._field == \"reply_time_ms\")\n  |> group(columns: [\"client\"])\n  |> aggregateWindow(every: 5m, fn: median)\n    |> set(key: \"client\", value: \"median\")"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.client =~ /^${client:regex}$/ and r._field == \"reply_time_ms\")\n  |> group(columns: [\"client\"])\n    |> aggregateWindow(\n        every: 5m,\n        fn: (tables=<-, column) => tables\n            |> quantile(q: 0.9, method: \"exact_selector\"),\n    )\n    |> set(key: \"client\", value: \"quantile 90%\")"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.client =~ /^${client:regex}$/ and r._field == \"reply_time_ms\")\n  |> group(columns: [\"client\"])\n    |> aggregateWindow(\n        every: 5m,\n        fn: (tables=<-, column) => tables\n            |> quantile(q: 0.95, method: \"exact_selector\"),\n    )\n    |> set(key: \"client\", value: \"quantile 95%\")"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.client =~ /^${client:regex}$/ and r._field == \"reply_time_ms\")\n  |> group(columns: [\"client\"])\n    |> aggregateWindow(\n        every: 5m,\n        fn: (tables=<-, column) => tables\n            |> quantile(q: 0.99, method: \"exact_selector\"),\n    )\n    |> set(key: \"client\", value: \"quantile 99%\")"
    }
   ]
  },
  {
   "title": "Reply time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.client =~ /^${client:regex}$/ and r._field == \"reply_time_ms\")\n  |> group(columns: [\"client\"])"
    }
   ]
  }
 ]
}