---
operator:
  replicas: 1
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      labels:
        release: system

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: system

hubble:
  enabled: true
  relay:
    enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        labels:
          release: system
  metrics:
    serviceMonitor:
      enabled: true
      labels:
        release: system
    enableOpenMetrics: true
    enabled:
      - dns
      - drop
      - tcp
      - icmp
      - "flow:sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
      - "kafka:labelsContext=source_namespace,source_workload,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
      - "httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
      # dns:
      # drop:
      # flow:
      # http:
      # icmp:
      # port-distribution:
      # tcp:
    dashboards:
      enabled: true
      namespace: system
      annotations:
        grafana_folder: "Hubble"
