---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    path: charts/cilium
    repoURL: https://github.com/yellowhat/argocd
    # repoURL: https://gitlab.com/yellowhat/mule.git
    targetRevision: main
  destination:
    namespace: cilium
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
