---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: pihole
    repoURL: https://gitlab.com/api/v4/projects/40025817/packages/helm/main
    targetRevision: 1.6.6
    helm:
      valueFiles:
        - ci/mule-values.yaml
  destination:
    namespace: pihole
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: false  # Disabled due to high cpu usage
    syncOptions:
      - CreateNamespace=true
