---
# Source: immich/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: immich-postgresql
  namespace: "immich"
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 16.4.0
    helm.sh/chart: postgresql-15.5.27
type: Opaque
data:
  postgres-password: "cGFzc3cwcmQ="
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
---
# Source: immich/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: immich-postgresql-svcbind-postgres
  namespace: "immich"
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 16.4.0
    helm.sh/chart: postgresql-15.5.27
type: servicebinding.io/postgresql
data:
  provider: "Yml0bmFtaQ=="
  type: "cG9zdGdyZXNxbA=="
  host: "aW1taWNoLXBvc3RncmVzcWw="
  port: "NTQzMg=="
  username: "cG9zdGdyZXM="
  database: "cG9zdGdyZXM="
  password: "cGFzc3cwcmQ="
  uri: "cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3MHJkQGltbWljaC1wb3N0Z3Jlc3FsOjU0MzIvcG9zdGdyZXM="
