---
# Source: system/charts/kube-prometheus-stack/charts/grafana/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system-grafana-clusterrolebinding
  labels:
    helm.sh/chart: grafana-8.4.4
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: system
    app.kubernetes.io/version: "11.1.3"
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: system-grafana
    namespace: system
roleRef:
  kind: ClusterRole
  name: system-grafana-clusterrole
  apiGroup: rbac.authorization.k8s.io
