---
# Source: system/charts/kube-prometheus-stack/charts/grafana/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: system-grafana
  namespace: system
  labels:
    helm.sh/chart: grafana-8.4.4
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: system
    app.kubernetes.io/version: "11.1.3"
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: cilium
  tls:
    - hosts:
      - grafana.mukka.haus
      secretName: grafana-tls
  rules:
    - host: "grafana.mukka.haus"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: system-grafana
                port:
                  number: 80
