---
# Source: system/charts/kube-prometheus-stack/charts/grafana/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: system-grafana
  namespace: system
  labels:
    helm.sh/chart: grafana-8.4.4
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: system
    app.kubernetes.io/version: "11.1.3"
    app.kubernetes.io/managed-by: Helm
rules: []
