{{- if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled }}
{{- with .Values.metrics.prometheusRule }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "blocky.fullname" $ }}
  labels:
    {{- include "blocky.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
    - name: {{ include "blocky.fullname" $ }}
      rules:
        - alert: BlockyAbsent
          annotations:
            description: Blocky has disappeared from Prometheus service discovery.
            summary: Blocky is down.
          expr: |
            absent(up{job=~".*{{ include "blocky.fullname" $ }}.*"} == 1)
          for: 5m
          labels:
            severity: critical
        - alert: BlockyDisabled
          annotations:
            description: Blocky's ad blocking has been disabled for 15min.
              Please re-enable protection.
            summary: Blocky is disabled.
          expr: |
            blocky_blocking_enabled{job=~".*{{ include "blocky.fullname" $ }}.*"} == 0
          for: 15m
          labels:
            severity: critical
        {{- with .rules }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
{{- end }}
