{
 "title": "Blocky",
 "description": "Metrics from blocky",
 "tags": [ "blocky" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(blocky_build_info, instance)"
    }
   },
   {
    "name": "client",
    "label": "Client",
    "query": {
     "query": "label_values(blocky_query_total, client)"
    }
   },
   { "name": "blocky_url", "label": "Blocky URL", "query": "http://blocky.lan" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running",
   "type": "stat",
   "description": "Current running status",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"blocky\"})"
    }
   ]
  },
  {
   "title": "Blocking",
   "type": "stat",
   "description": "Is blocking enabled?",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blocky_blocking_enabled{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Time since last list refresh",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - blocky_last_list_group_refresh{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Domains on Blacklist",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blocky_blacklist_cache{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Error count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blocky_error_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total queries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(blocky_query_total{instance=~\"$instance\", client=~\"$client\"})"
    }
   ]
  },
  {
   "title": "Total Blocked (all)",
   "type": "stat",
   "description": "Total blocked request for all clients",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(blocky_response_total{instance=~\"$instance\", response_type=\"BLOCKED\"})"
    }
   ]
  },
  {
   "title": "Cached entries (all)",
   "type": "stat",
   "description": "Cached entries for all clients",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "blocky_cache_entry_count{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Cache Hit/Miss ratio (all)",
   "type": "stat",
   "description": "Cache Hit/Miss ratio. 100 % means, all queries could be answered from the cache, 0% - all queries must be resolved via external DNS",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "blocky_cache_hit_count{instance=~\"$instance\"} / (blocky_cache_hit_count{instance=~\"$instance\"} + blocky_cache_miss_count{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Memory allocated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "GO Routine",
   "type": "stat",
   "description": "Number of goroutines that currently exist",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "GO Threads",
   "type": "stat",
   "description": "Number of threads that currently exist",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_threads{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Enable/Disable blocking",
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": {
    "content": "<style>\n\t#status-box {\n\t    display: inline-block;\n\t    padding: 10px;\n\t    border-radius: 5px;\n\t    font-size: 18px;\n\t    font-weight: bold;\n\t    text-align: center;\n\t    min-width: 100px;\n\t    color: white;\n\t}\n\t.success {\n\t    background-color: green;\n\t}\n\t.failure {\n\t    background-color: red;\n\t}\n\n\t.blocky_btn {\n\t    border: none;\n\t    cursor: pointer;\n\t    padding: 12px;\n\t    border-radius: 5px;\n\t    font-size: 16px;\n\t    min-width: 100px\n\t    color: white;\n\t}\n\n\t.blocky_greenbtn {\n\t    background-color: #ccffcc;\n\t}\n\n\t.blocky_redbtn {\n\t    background-color: #ff9999;\n\t}\n\n\t.blocky_alert {\n\t    font-size: 14px\n\t}\n</style>\n\n<div class=\"blocky_alert blocky_alert-warning fade in\"><a href=\"#\" class=\"close\" data-dismiss=\"blocky_alert\" aria-label=\"close\" style=\"text-decoration:none\">&times;</a>Done!</div>\n<div>\n\t<div id=\"status-box\" class=\"failure\">\n\t\t<span id=\"status-text\"></span>\n\t</div>\n\t<button class=\"blocky_btn blocky_greenbtn\" onclick=\"set_enabled()\">On</button>\n\t<button class=\"blocky_btn blocky_redbtn\" onclick=\"set_disabled()\">Off</button>\n\t<button class=\"blocky_btn blocky_redbtn\" onclick=\"set_disabled_5m()\">Off 5m</button>\n\t<button class=\"blocky_btn blocky_redbtn\" onclick=\"set_disabled_30m()\">Off 30m</button>\n\t<div>\n\t\t<script type=\"text/javascript\">\n            function get_status() {\n                var url = \"$blocky_url\" + \"/api/blocking/status\";\n                fetch(url)\n                    .then(response => response.json())\n                    .then(data => {\n                        const statusText = document.getElementById(\"status-text\");\n                        const statusBox = document.getElementById(\"status-box\");\n                        if (data.enabled === true) {\n                            console.log(\"Set status to on\")\n                            statusBox.classList.add(\"success\");\n                            statusBox.classList.remove(\"failure\");\n                            statusText.innerText = \"Currently on\";\n                        } else {\n                            console.log(\"Set status to off\")\n                            statusBox.classList.add(\"failure\");\n                            statusBox.classList.remove(\"success\");\n                            statusText.innerText = \"Currently off\";\n                        }\n                })\n                .catch(error => console.error(error));\n            }\n\n            function set_disabled() {\n                switch_status(false, 0)\n            }\n\n            function set_disabled_5m() {\n                switch_status(false, 5*60)\n            }\n\n            function set_disabled_30m() {\n                switch_status(false, 30*60)\n            }\n\n            function set_enabled() {\n                switch_status(true, 0)\n            }\n\n            function switch_status(enable, duration) {\n                op = enable ? \"enable\" : \"disable?duration=\" + duration + \"s\"\n                var url = \"$blocky_url\" + \"/api/blocking/\" + op;\n                fetch(url)\n                             .then(response => {\n                                 showAlert()\n                                 get_status()\n                             })\n                    .catch(error => alert(\"URL: \" + url + \"\\n\" + \"error: \" + error));\n            }\n\n            var showAlert = function() {\n                // first show the alert\n                $(\".blocky_alert\").show().fadeTo(500, 1);\n\n                // Now set a timeout to hide it\n                window.setTimeout(function() {\n                    $(\".blocky_alert\").fadeTo(500, 0).slideUp(500, function() {\n                    $(this).hide();\n                    });\n                }, 2000);\n            }\n\n            // Get current status\n            get_status()\n\n            // start with the alert hidden\n            $(\".blocky_alert\").hide();\n\t\t</script>\n\t</div>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (client) (blocky_query_total{instance=~\"$instance\", client=~\"$client\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prefetch count (all)",
   "type": "stat",
   "description": "Amount of performed DNS queries to prefetch cached queries for all clients",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blocky_prefetch_count{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Prefetch Hit ratio (all)",
   "type": "stat",
   "description": "How many of cached entries were prefetched automatically for all clients",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "blocky_prefetch_hit_count{instance=~\"$instance\"} / blocky_cache_hit_count{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Prefetch rate per min (all)",
   "type": "stat",
   "description": "Amount of prefetch queries per minute for all clients",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(blocky_prefetch_count{instance=~\"$instance\"}[5m])) * 60"
    }
   ]
  },
  {
   "title": "Prefetch domain count (all)",
   "type": "stat",
   "description": "Amount of unique domains in the prefetched cache for all clients",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blocky_prefetch_domain_name_cache_count"
    }
   ]
  },
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Clients - all",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (client_names, client_ip) (\n    count_over_time(\n        {app=\"blocky\"} | json | prefix = \"queryLog\" | client_names =~ \"$client\" [$__range]\n    )\n)"
    }
   ]
  },
  {
   "title": "Clients - blocked",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (client_names, client_ip) (\n    count_over_time(\n        {app=\"blocky\"} | json | prefix = \"queryLog\" | client_names =~ \"$client\" | response_type = \"BLOCKED\" [$__range]\n    )\n)"
    }
   ]
  },
  {
   "title": "Domains - all",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (question_name) (\n    count_over_time(\n        {app=\"blocky\"} | json | prefix = \"queryLog\" | client_names =~ \"$client\" [$__range]\n    )\n)"
    }
   ]
  },
  {
   "title": "Domains - blocked",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "sum by (question_name) (\n    count_over_time(\n        {app=\"blocky\"} | json | prefix = \"queryLog\" | client_names =~ \"$client\" | response_type = \"BLOCKED\" [$__range]\n    )\n)"
    }
   ]
  },
  {
   "title": "Request - per client (5 min window)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (client_names) (\n    count_over_time(\n        {app=\"blocky\"} | json | prefix = \"queryLog\" | client_names =~ \"$client\" [5m]\n    )\n)",
     "legendFormat": "{{ client_names }}"
    }
   ]
  },
  {
   "title": "Request - per response type (5 min window)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (response_type) (\n    count_over_time(\n        {app=\"blocky\"} | json | prefix = \"queryLog\" | client_names =~ \"$client\" [5m]\n    )\n)",
     "legendFormat": "{{ response_type }}"
    }
   ]
  },
  { "title": "Pie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Request per client",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (client_names) (\n    count_over_time(\n        {app=\"blocky\"} | json | prefix = \"queryLog\" | client_names =~ \"$client\" [$__range]\n    )\n)",
     "legendFormat": "{{ client_names }}"
    }
   ]
  },
  {
   "title": "Request type",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (question_type) (\n    count_over_time(\n        {app=\"blocky\"} | json | prefix = \"queryLog\" | client_names =~ \"$client\" [$__range]\n    )\n)",
     "legendFormat": "{{ question_type }}"
    }
   ]
  },
  {
   "title": "Response type",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (response_type) (\n    count_over_time(\n        {app=\"blocky\"} | json | prefix = \"queryLog\" | client_names =~ \"$client\" [$__range]\n    )\n)",
     "legendFormat": "{{ response_type }}"
    }
   ]
  },
  {
   "title": "Response code",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (response_code) (\n    count_over_time(\n        {app=\"blocky\"} | json | prefix = \"queryLog\" | client_names =~ \"$client\" [$__range]\n    )\n)",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "Upstream",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (upstream) (\n    count_over_time(\n        {app=\"blocky\"} | regexp `\"response_reason\":\".*\\s+\\((?P<upstream>\\S+)\\)` | json | prefix = \"queryLog\" | client_names =~ \"$client\" | upstream != \"\" [$__range]\n    )\n)",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  { "title": "Response time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Response time - raw",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(\n    {app=\"blocky\"} | json | prefix = \"queryLog\" | client_names =~ \"$client\" | response_type = \"RESOLVED\" | unwrap duration_ms | __error__ = \"\" [1s]\n)",
     "legendFormat": "{{ question_name }} | {{ client_names }}"
    }
   ]
  },
  {
   "title": "Response time - max (1m window)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (client_names) (\n    max_over_time(\n        {app=\"blocky\"} | json | prefix = \"queryLog\" | client_names =~ \"$client\" | response_type = \"RESOLVED\" | unwrap duration_ms | __error__ = \"\" [1m]\n    )\n)",
     "legendFormat": "{{ client_name }}"
    }
   ]
  },
  {
   "title": "Response time - p95 (1m window)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile_over_time(\n    0.95,\n    {app=\"blocky\"} | json | prefix = \"queryLog\" | client_names =~ \"$client\" | response_type = \"RESOLVED\" | unwrap duration_ms | __error__ = \"\" [1m]\n) by (client_names)",
     "legendFormat": "{{ client_names }}"
    }
   ]
  },
  {
   "title": "Response time - p95 (1m window) per upstream",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile_over_time(\n    0.95,\n    {app=\"blocky\"} | regexp `\"response_reason\":\".*\\s+\\((?P<upstream>\\S+)\\)` | json | prefix = \"queryLog\" | client_names =~ \"$client\" | response_type = \"RESOLVED\" | unwrap duration_ms | __error__ = \"\" [5m]\n) by (upstream)",
     "legendFormat": "{{ client_names }}"
    }
   ]
  },
  { "title": "Tail logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "{app=\"blocky\"} | regexp `\"response_reason\":\".*\\s+\\((?P<upstream>\\S+)\\)` | json | prefix = \"queryLog\" | client_names =~ \"$client\""
    }
   ]
  },
  {
   "title": "Error/Warnings",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 117 },
   "targets": [
    {
     "expr": "{app=\"blocky\"} != `answer` != `info`"
    }
   ]
  },
  {
   "title": "Pie (Prometheus)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response type (all)",
     "type": "piechart",
     "description": "Response type for all clients",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (response_type) (ceil(increase(blocky_response_total{instance=~\"$instance\"}[$__range]))))",
       "legendFormat": "{{response_type}}"
      }
     ]
    },
    {
     "title": "Response code (all)",
     "type": "piechart",
     "description": "Response code for all clients",
     "gridPos": { "h": 10, "w": 5, "x": 6, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (response_code) (ceil(increase(blocky_response_total{instance=~\"$instance\"}[$__range]))))",
       "legendFormat": "{{response_code}}"
      }
     ]
    },
    {
     "title": "Query by type",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 6, "x": 11, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (type) (ceil(increase(blocky_query_total{instance=~\"$instance\", client=~\"$client\"}[$__range]))))",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Query per Client",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 7, "x": 17, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (client) (ceil(increase(blocky_query_total{instance=~\"$instance\", client=~\"$client\"}[$__range]))))",
       "legendFormat": "{{ client }}"
      }
     ]
    },
    {
     "title": "Response Reasons",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (reason) (ceil(increase(blocky_response_total{instance=~\"$instance\"}[$__range]))))",
       "legendFormat": "{{reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Response (Prometheus)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg response time",
     "type": "timeseries",
     "description": "Average query response time for all query types",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(blocky_request_duration_ms_sum{instance=~\"$instance\"}[1m]) / rate(blocky_request_duration_ms_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{ response_type }}"
      }
     ]
    },
    {
     "title": "Request rate per client",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (client) (rate(blocky_query_total{instance=~\"$instance\", client=~\"$client\"}[1m]))",
       "legendFormat": "{{ client }} {{ type }} "
      }
     ]
    },
    {
     "title": "Request duration (upstream)",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 140 },
     "targets": [
      {
       "expr": "sum(blocky_request_duration_ms_bucket{response_type=\"RESOLVED\"}) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}