---
{{- if .Values.admin.existingSecret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.admin.existingSecret }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      name: {{ .Values.admin.existingSecret }}
      namespace: {{ .Release.Namespace }}
  encryptedData:
    password: AgB7jsTjA2xTqztQ8JMyl/ulgjNRctH9TvOPoU5XuIIrVzXAsg0SLHi3CyjO1nfcu68SIHbyHANv/Qh9CW231mqk4aoyKvcOlJqy6ib65f1PeyYidFg51ksqK3RKY9HqxNIJx70JQcM5JFz/otQuw+wZfBTVG9M1XZMM1ojnaUSUnaxKjJxEqrLZWvcib1S7MHodWs81JtPjFYyXMsJsghNfGqDrXhxim+REngEk+FFUj5F5T6/NVu6BHfrRptrj4BpoMHAB5ukGFSer6rA/b7/b+eNnhR9VggY9Rzbr7Fn/6iXHnxxUcWxNn+I5rxKfah5jQuJzWKKrXQTgTtBKH1ACrtfOXL3/PUqyepWzUsZDyHUqbr2KcMMh8pbTnFTK2o3cNh0pw6WPUt9vkGPZbIrBHr1eZRAbOJQN06ToFzSuAZYY+/kkJeU05YXwX88rGSsmu3aHVWanXQ4SxgLPzNy9nFH+89I+E24Kl6i1yNCfinE7v1dVHpVxk8l3FTM6n5ub1wByXmwue962z0uQbwG3JPkc4Lzy2dgOD+KOIB7pllQT9/Klut84J+5HLnw1oW8AEf72ARDCWmgTbS56clPezCBL72RDtgAxp19DeVCaHep1i5Z/on07UN5gr2UTC0eXCI4VYhjPEIcPry0EfMRo1t/EZcTIMcj3vQltQSI5V1Uzql9Zt6mxl6rY+gFOXZEok8R34m0=
{{- end }}
