---
# Source: system/charts/kube-prometheus-stack/charts/prometheus-node-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: system-prometheus-node-exporter
  namespace: system
  labels:
    helm.sh/chart: prometheus-node-exporter-4.37.3
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: prometheus-node-exporter
    app.kubernetes.io/name: prometheus-node-exporter
    app.kubernetes.io/instance: system
    app.kubernetes.io/version: "1.8.2"
    jobLabel: node-exporter
    release: system
automountServiceAccountToken: false
