---
# Source: system/charts/loki/templates/single-binary/service-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: loki-headless
  namespace: system
  labels:
    helm.sh/chart: loki-6.10.0
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: system
    app.kubernetes.io/version: "3.1.1"
    app.kubernetes.io/managed-by: Helm
    variant: headless
    prometheus.io/service-monitor: "false"
  annotations:
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 3100
      targetPort: http-metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: system
