---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pigallery2.fullname" . }}-config
  labels:
    {{- include "pigallery2.labels" . | nindent 4 }}
data:
  config.json: |
{{ $.Files.Get "ci/config.json" | indent 4 }}
