---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jellyfin-config
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config
  labels:
    type: local
spec:
  storageClassName: jellyfin-config
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/data/jellyfin-config"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: disk
              operator: In
              values:
                - local
