---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: loki
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki
  labels:
    type: local
spec:
  storageClassName: loki
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /data/loki
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: disk
              operator: In
              values:
                - local
