{{- with .Values.persistence }}
{{- if and .enabled ( not .existingClaim ) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "pihole.fullname" . }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .size | quote }}
{{- end }}
{{- end }}
