---
{{- if .Values.admin.existingSecret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin
  namespace: pihole
spec:
  template:
    metadata:
      name: pihole-admin
      namespace: pihole
  encryptedData:
    password: AgCyJHpvmKU2YJzjrU8lnA4ob73y7hw7w91Jz6BxZfeMQttpvS5T9Hlo5LalEOCQCIT1yL+KMbBqjWrbFtbG07gkMoHptM1LAlgjlTPDgyGU5rSyx0TuJhHc7dwzwT4YzrgAwiR3bdR38wWPknBSTyPDDiS4950d/c5eDfIUFq4rlA7VdiXpZRqe20hrfqm8xyeaQ26gMXbChv55+USOm8tcfVUwa1wj4B0bEffwA9NZjuqJWlUCfd/8fOFCVg/oMH02GVPnH92zWKVxR2WlWPJxjf+FpE4+/guGB4cAkmpVI3pL0mChIn9AdPekKElhxee1qIPU2H3JGPmRJ9ZGYkXvlHMxcHOEyBat6LWLPe5YSKILA8Lxt7lw5rO9Y8hm65ih46K3O97PfMbzaC+RdSFkjmK9XpcfKkHdDaIdkRLUSO6R3zom/4VJa3MyZLdWxn6IGJmVA/1N9f5QYAg3qufcORdeEjiQpVI9hgV7jAY9gaRhDF9dsRqa7Gs60GeoQz3kTq8jhFubvkiS6XAq/4D5zSgxUcvy7go7/cmy4UE53AUR377Hl+ODxTcTb09M97LJJ7iEsgl/nRx7QqeSMIaBhq//WAl+/QUAaTVCtElzMH1Dlla7F49kQ3FRdmtAEDzwkBuPoMrc/MHWxG7xbGSnEIpCKorCERLwpw7Ub9lJq7CkwaYjDpnYH++tD+oAlWrNI7n2wYw=  # pragma: allowlist secret
{{- end }}
