---
{{- if not .Values.serviceDns.mixedService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.fullname" . }}-dns-udp
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
  {{- with .Values.serviceDns.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.serviceDns.type }}
  {{- if and (.Values.dualStack.enabled) (not (eq .Values.serviceDns.type "LoadBalancer")) }}
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: PreferDualStack
  {{- end }}
  {{- if or (eq .Values.serviceDns.type "NodePort") (eq .Values.serviceDns.type "LoadBalancer") }}
  externalTrafficPolicy: {{ .Values.serviceDns.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.serviceDns.port }}
      targetPort: dns-udp
      {{- if and (.Values.serviceDns.nodePort) (eq .Values.serviceDns.type "NodePort") }}
      nodePort: {{ .Values.serviceDns.nodePort }}
      {{- end }}
      protocol: UDP
      name: dns-udp
  selector:
    {{- include "pihole.selectorLabels" . | nindent 4 }}

---
{{- if and (.Values.dualStack.enabled) (eq .Values.serviceDns.type "LoadBalancer") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "pihole.fullname" . }}-dns-udp-ipv6
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
  {{- with .Values.serviceDns.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.serviceDns.type }}
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  {{- if or (eq .Values.serviceDns.type "NodePort") (eq .Values.serviceDns.type "LoadBalancer") }}
  externalTrafficPolicy: {{ .Values.serviceDns.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.serviceDns.port }}
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
  selector:
    {{- include "pihole.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}
