---
{{- if not .Values.serviceDns.mixedService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.fullname" . }}-dns-tcp
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
  {{- with .Values.serviceDns.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.serviceDns.type }}
  {{- if and (.Values.dualStack.enabled) (not (eq .Values.serviceDns.type "LoadBalancer")) }}
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: PreferDualStack
  {{- end }}
  {{- if or (eq .Values.serviceDns.type "NodePort") (eq .Values.serviceDns.type "LoadBalancer") }}
  externalTrafficPolicy: {{ .Values.serviceDns.externalTrafficPolicy }}
  {{- end }}
  ports:
    - name: dns
      port: {{ .Values.serviceDns.port }}
      targetPort: dns
      {{- if and (.Values.serviceDns.nodePort) (eq .Values.serviceDns.type "NodePort") }}
      nodePort: {{ .Values.serviceDns.nodePort }}
      {{- end }}
      protocol: TCP
    {{- if .Values.monitoring.sidecar.enabled }}
    - name: prometheus
      port: {{ .Values.monitoring.sidecar.port }}
      targetPort: prometheus
      protocol: TCP
    {{- end }}
  selector:
    {{- include "pihole.selectorLabels" . | nindent 4 }}

---
{{- if and (.Values.dualStack.enabled) (eq .Values.serviceDns.type "LoadBalancer") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "pihole.fullname" . }}-dns-tcp-ipv6
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
  {{- with .Values.serviceDns.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.serviceDns.type }}
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  {{- if or (eq .Values.serviceDns.type "NodePort") (eq .Values.serviceDns.type "LoadBalancer") }}
  externalTrafficPolicy: {{ .Values.serviceDns.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.serviceDns.port }}
      targetPort: dns
      protocol: TCP
      name: dns
    {{- if .Values.monitoring.sidecar.enabled }}
    - port: {{ .Values.monitoring.sidecar.port }}
      targetPort: prometheus
      protocol: TCP
      name: prometheus
    {{- end }}
  selector:
    {{- include "pihole.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}
