---
# Source: system/charts/loki/templates/service-memberlist.yaml
apiVersion: v1
kind: Service
metadata:
  name: loki-memberlist
  namespace: system
  labels:
    helm.sh/chart: loki-6.10.0
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: system
    app.kubernetes.io/version: "3.1.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp
      port: 7946
      targetPort: http-memberlist
      protocol: TCP
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: system
    app.kubernetes.io/part-of: memberlist
