---
# Source: argo-cd/charts/argo-cd/templates/argocd-application-controller/metrics.yaml
apiVersion: v1
kind: Service
metadata:
  name: argo-cd-application-controller-metrics
  namespace: argo-cd
  labels:
    helm.sh/chart: argo-cd-7.4.1
    app.kubernetes.io/name: argo-cd-metrics
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: "v2.12.0"
spec:
  type: ClusterIP  
  ports:
  - name: http-metrics
    protocol: TCP
    port: 8082
    targetPort: metrics
  selector:
    app.kubernetes.io/name: argo-cd-application-controller
    app.kubernetes.io/instance: argo-cd
