---
{{- if index .Values "kube-prometheus-stack" "grafana" "admin" "existingSecret" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ index .Values "kube-prometheus-stack" "grafana" "admin" "existingSecret" }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      name: {{ index .Values "kube-prometheus-stack" "grafana" "admin" "existingSecret" }}
      namespace: {{ .Release.Namespace }}
  encryptedData:
    username: AgBRyOa+HXROmmeNwoSiAG2sVd3AyRCTsBQSeAp8QHRloRQSajp8Oahq6baxpOw8hBZKxVYZmaGrqlYjsSEaVMUQ/S7f3vAy22oB18O9Vg4us85sZ3oIvORqlOgFR70mD2vLlQumqXT38O7I44G+yjO1itpkdgfp/mQ1C51nw+0Sswlui5QXD2n18VAQKN+HlJjts1lEdhtVFpbHxmNlh7PqJ++ajiS5ZaR0rFVt3537Xuizt6Zjc9yvSBgm0Eu/WVHGXLrPVA8/EtKmIfmJZd+uYFeMzUJTc2BxdIWXtaIAbvI8vrDuoQp7do67mmU9aenNQ+s6xQ0nVrv+p5rfh+0n8EzmrjhSFIPOWyZUVh/lXICSq2te8vFWXd1JFcIeAvXbPK1ceSKHGenH7aKbHd+GvcPXhOH8MRVUcM3mEh8283y+cyC/TTPw913k1uYHmdMYFnpzop7UXTBfaPpuT/k9cnjxVJNxAkjGXMi2AkiTINDpo+N3nN3v4X5MdgO5mBIxDXo3vtE8pD6LiOJrbgtDeHiCFLkS5oMEUBxayXrBBnt5UYw/n3SLxBmYBeAGxJ9JS0lPWJQyVSrd7/VmCjvgU26fco7hknMh9BXfpB1Xppu90AxR+gKy0W6+TJT36RrUSpf+rk6RgDpg2qFNcyjfkVKv4ZZL5K5ELmycjLNJCBIKkOh/1EHkCN9/BcaNGsCcW+o26A==
    password: AgCaFZjlyBYlvLhQyNXWLvPwnUHWHKiNv7jHhMQ1783R2TOx3TI6Pbd+hKWMx90Nbm58eJ/TyPvZBR6PlF/qHuweN8ZaLgYiybClBwSlaZd6dN2FikdYsXP2fL+mg4I7We3Gz/6rPdjOvdnRELTGkGlNgtynfH8DKdPR+Ime4CUxq+f5B7C+uhpzanEbpmk/ePz+IrhuPWEw5NkNyJdNBL6FZXSmLx8SXnbXHMz02Hu/BpsK3AOGme5KdoQKDQF6xYMKklYE71AGGfQbjwo5jEDBJotHxdQFj9fS5A213HOXd9pwAYEHXLOt3alTU3bYV3BfBC5ImMvW7NWBkL1yIOULgDspCwbC1eZgKVV3SgaPfVt/POEOAA0bLylYOZTwFx3avQGGoH8sLEvUFTk+ByLSmwKsX948OKVhU4LCBDDv5El5MDVTjCv/Dlx7HyP2ug7g5yNp7O8sRTwlRlZOwRGyY28+jUJcheb/Q7biF9swunVmWjMsixDFBNlbroPX8X6syo90ByNb8VbGFBT5c4gsJK+ocUw+d4n6EoDOVPMc4ukgMyDdfpisxdcxM5pJ+UEmEJGAjsCb+r/eXButh/Lkyg8WXrQXVKUo0vFBzW3HiMIm9CGkM4mdkSc11q/iM3FG2i/WbFRHq756X/7n3pUJBGrwyY2CwiRomGfrPQNyEaEfC5Zu5JNQwgKezFPkINrkn2cF+Ukf
{{- end }}
