---
{{- if index .Values "kube-prometheus-stack" "grafana" "admin" "existingSecret" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ index .Values "kube-prometheus-stack" "grafana" "admin" "existingSecret" }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      name: {{ index .Values "kube-prometheus-stack" "grafana" "admin" "existingSecret" }}
      namespace: {{ .Release.Namespace }}
  encryptedData:
    username: AgB5b1YCUIohnsewRwrOtIn67YRnnq33spuToi7AZiMoYyN+Pnmygh09RiBYCr9ihxeGpZZJ95UujbU42ujtWgxiEDbBgzws7sYfF1K2vQSirTl9tfsx2Bgp004E0zLInvURq4JXVhSFRW5pk2RZ8qtWVZKYe4bjR/a9YTqblpdvJahzGFZ7VISk4f3BJHxtE/hgzBIhITbmLMp9lVdwj0p23AODyr46HhrV8x41DkmeVYCpqKufBfus8ksM2r7H7pLMwg0FUUZ2JRauRFdr+ZX1N1sRJlTXKCLazb5ArqCX4cKqe8gLHeIpeV8GBsv1XTWF8MHHR1r/GV7uUUUufsh0F4fNbwi5vfbJWN0ptAnDmenfzayYNjNhw8hBzS/qw0+K2TgLEIkuJy2mhmXH6NsxKuKVP1L4vEY0Q7Ltrk8FF2w8sOP+scyWMTaMELnh0mUWsMHleiXL6hj5IW8ET9QUZrngt3VqFrpMkV4Bth1FPTFyAiiNL/4hj9HEwIn4gj/7trU6w9lr5HaCyhawao+YuDmx9JSNKOf4CAOutf7e4TWQCnfPsNK6pqbX1rvxKAOhQuWklz/+2kYfwTDh7EfXb5o73Tm3Nsch3oZrc5BfV/Drl1Z2+6m251kHiAhUw03TQmfoYbei0UGVdkULyPe9Xe3kHHpDbjF4+00jhwzuaYKqsYci3scjCk0vJ5xbGp13ITYQVw==
    password: AgAGi9lWtv6+vb3kynUPJQPBZ//tV65zWp7Gk1a40oL+BNvVWklXGBmkV8qY1kKuJWzcov5ed3mM4t32G68NVQea6Se3f0Jc7JEtOKzbUjXyG9vaQUXshN/e26bljsqQjN9+4Q11+hMohT1aPSSb2l1/lccFi6+ap58kZ0zomkMXksiK43W4+KdSKCypd99CraZa1fGD6KGMTntsIWsIz+RHAT7dRofMMUzfpN22YZhd99xA0zTOTo660/Mfo40pp+QAz3HZ+cpP65Om8kquR+UY0CspZQPJw8lv5lKLekP+AI5rTLvgc1NtOsGuaSlA2ROPNW21c++5W0qf3dnW/92I1NY0b1I3byCaOR9pf6x7neYLWrLeYwGm4rQ0ojDm0CSuXcs9Z1Tw2SXjyelf4KM4P4gt18oWBmW1grCjlPqzaF8CHOfVbt199kJ/jBitbEJrrx9H4LHUnxUwsmQnXLUxOS7EtFmpEljSer4WZXVCqy8QoZECbhvv8J1vj69Vp3iI8CK7JX9j8u4QUC8x8AXtROaSLGsqjjbFWO+hHlPoN9FGsouhIoe5r5ZWu/SLW8dCPw0z+VHhnZgCsyINI2Kctk8MC3NuCL5Eim3iD5hHW3MmtfuyAHZyarSThjgj/RRUlC13KXBAFDO87nwMq5fzZxnwut+CCKMwabpH3gMuDwH3AB+WtEXzW6qpcyMGAGa3NqJE/kJ9
{{- end }}
