---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    # Use foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: manifests/argo-cd
    repoURL: https://github.com/yellowhat/argocd
    # repoURL: https://gitlab.com/yellowhat-labs/mule.git
    targetRevision: HEAD
    directory:
      recurse: true

    # path: charts/argo-cd
    # repoURL: https://github.com/yellowhat/argocd
    # # repoURL: https://gitlab.com/yellowhat-labs/mule.git
    # targetRevision: main
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: false  # Disabled due to high cpu usage
    syncOptions:
      - CreateNamespace=true
