apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: app-of-apps
  namespace: argocd
spec:
  source:
    path: metallb-CRs
    repoURL: "https://github.com/yellowhat/argocd"
    targetRevision: HEAD
  destination:
    namespace: metallb
    server: "https://kubernetes.default.svc"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
