---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: pihole
  namespace: argocd
spec:
  project: default
  source:
    path: charts/pihole
    repoURL: https://github.com/yellowhat/argocd
    # repoURL: https://gitlab.com/yellowhat/mule.git
    targetRevision: main
    helm:
      valueFiles:
        - ci/mule-values.yaml
  destination:
    namespace: pihole
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
