{
 "title": "eBPF-exporter",
 "description": "Metrics from ebpf-exporter",
 "tags": [ "ebpf" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Node",
    "query": {
     "query": "label_values(ebpf_exporter_build_info,hostname)"
    }
   },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(ebpf_exporter_bio_latency_seconds_sum{hostname=~\"$hostname\"}, device)"
    }
   },
   {
    "name": "port",
    "label": "Port",
    "query": {
     "query": "label_values(ebpf_exporter_accept_latency_seconds_count{hostname=\"$hostname\"},port)"
    }
   }
  ]
 },
 "panels": [
  { "title": "eBPF enabled config", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "eBPF enabled config: ${hostname}",
   "type": "status-history",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "repeat": "hostname",
   "targets": [
    {
     "expr": "ebpf_exporter_enabled_configs{hostname=~\"$hostname\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "BIO Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "biolatency read",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bio_latency_seconds_bucket{operation=\"read\", hostname=~\"$hostname\", device=~\"$device\"}[4m])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "biolatency write",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bio_latency_seconds_bucket{operation=\"write\", hostname=~\"$hostname\", device=~\"$device\"}[4m])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "biolatency flush",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bio_latency_seconds_bucket{operation=\"flush\", hostname=~\"$hostname\", device=~\"$device\"}[4m])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Percentiles and average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(ebpf_exporter_bio_latency_seconds_bucket{hostname=~\"$hostname\", device=~\"$device\"}[4m]) )",
     "legendFormat": "90% {{operation}} {{device}}"
    },
    {
     "expr": "histogram_quantile(0.95, rate(ebpf_exporter_bio_latency_seconds_bucket{hostname=~\"$hostname\", device=~\"$device\"}[4m]) )",
     "legendFormat": "95% {{operation}} {{device}}"
    },
    {
     "expr": "rate(ebpf_exporter_bio_latency_seconds_sum{hostname=~\"$hostname\", device=~\"$device\"}[4m]) / rate(ebpf_exporter_bio_latency_seconds_count{hostname=~\"$hostname\", device=~\"$device\"}[4m])",
     "legendFormat": "{{operation}} {{device}} average"
    }
   ]
  },
  {
   "title": "Accept Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Accept Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_accept_latency_seconds_count{hostname=~\"$hostname\", port=~\"$port\"}[4m])",
     "legendFormat": "avg {{hostname}} {{port}}"
    }
   ]
  },
  {
   "title": "90% Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(ebpf_exporter_accept_latency_seconds_bucket{hostname=~\"$hostname\", port=~\"$port\"}[4m]))",
     "legendFormat": "90% accept {{hostname}} {{port}}"
    }
   ]
  },
  {
   "title": "99% Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(ebpf_exporter_accept_latency_seconds_bucket{hostname=~\"$hostname\", port=~\"$port\"}[4m]))",
     "legendFormat": "95% accept {{hostname}} {{port}}"
    }
   ]
  },
  {
   "title": "Averages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_accept_latency_seconds_sum{hostname=~\"$hostname\", port=~\"$port\"}[4m]) / rate(ebpf_exporter_accept_latency_seconds_count{hostname=~\"$hostname\", port=~\"$port\"}[4m])",
     "legendFormat": "avg accept {{hostname}} {{port}}"
    }
   ]
  },
  { "title": "JIT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "JIT pages allocated",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bpf_jit_pages_currently_allocated{hostname=~\"$hostname\"}[4m])",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  { "title": "Cgroup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Cgroup Sched Migrations",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_cgroup_sched_migrations_total{hostname=~\"$hostname\"}[4m])",
     "legendFormat": "{{ hostname }} - {{ cgroup }}"
    }
   ]
  },
  { "title": "Program", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "eBPF Program",
   "type": "status-history",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "sum by (program) (ebpf_exporter_ebpf_program_info{hostname=~\"$hostname\"})",
     "legendFormat": "{{ program }}"
    }
   ]
  },
  {
   "title": "eBPF Program Attached",
   "type": "status-history",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 113 },
   "targets": [
    {
     "expr": "sum by (id) (ebpf_exporter_ebpf_program_attached{hostname=~\"$hostname\"})",
     "legendFormat": "pid {{ id }}"
    }
   ]
  },
  { "title": "PageCache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 } },
  {
   "title": "Page Cache OPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum by (hostname, op) (rate(ebpf_exporter_page_cache_ops_total{hostname=~\"$hostname\"}[4m]))",
     "legendFormat": "{{ hostname }} - {{ op }}"
    }
   ]
  },
  { "title": "Timer Starts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 } },
  {
   "title": "Raw timer Starts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (hostname, function) (rate(ebpf_exporter_raw_timer_starts_total{hostname=~\"$hostname\"}[4m]))",
     "legendFormat": "{{ hostname }} - {{ function }}"
    }
   ]
  },
  {
   "title": "Timer Starts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (hostname, function) (rate(ebpf_exporter_timer_starts_total{hostname=~\"$hostname\"}[4m]))",
     "legendFormat": "{{ hostname }} - {{ function }}"
    }
   ]
  },
  { "title": "ShrinkNodeLatencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 } },
  {
   "title": "Percentiles and average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(ebpf_exporter_shrink_node_latency_seconds_bucket{hostname=~\"$hostname\"}[4m]))",
     "legendFormat": "90% {{ hostname }}"
    },
    {
     "expr": "histogram_quantile(0.95, rate(ebpf_exporter_shrink_node_latency_seconds_bucket{hostname=~\"$hostname\"}[4m]))",
     "legendFormat": "95% {{ hostname }}"
    },
    {
     "expr": "rate(ebpf_exporter_shrink_node_latency_seconds_sum{hostname=~\"$hostname\"}[4m]) / rate(ebpf_exporter_shrink_node_latency_seconds_count{hostname=~\"$hostname\"}[4m])",
     "legendFormat": "avg {{ hostname }}"
    }
   ]
  },
  { "title": "TcpSynBacklog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 163 } },
  {
   "title": "Percentiles and average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(ebpf_exporter_tcp_syn_backlog_bucket{hostname=~\"$hostname\"}[4m]))",
     "legendFormat": "90% {{hostname}} "
    },
    {
     "expr": "histogram_quantile(0.95, rate(ebpf_exporter_tcp_syn_backlog_bucket{hostname=~\"$hostname\"}[4m]))",
     "legendFormat": "95% {{hostname}}"
    },
    {
     "expr": "rate(ebpf_exporter_tcp_syn_backlog_sum{hostname=~\"$hostname\"}[4m]) or rate(ebpf_exporter_tcp_syn_backlog_count{hostname=~\"$hostname\"}[4m])",
     "legendFormat": "avg {{hostname}}"
    }
   ]
  },
  { "title": "TcpWindowClamps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 173 } },
  {
   "title": "TCP Window Clamps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 174 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (hostname) (rate(ebpf_exporter_tcp_window_clamps_total{hostname=~\"$hostname\"}[4m]))",
     "legendFormat": "{{ hostname }}"
    }
   ]
  }
 ]
}