kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  labels:
{{- include "labels" .| nindent 4 }}
spec:
  storageClassName: {{ .Values.dataVolume.storageClassName }}
  accessModes:
    {{- toYaml .Values.dataVolume.accessModes | nindent 4 }}
  resources:
    requests:
      storage: "{{ .Values.dataVolume.size }}"
