---
cilium:
  rollOutCiliumPods: true

  # Required to enable `ingressController`
  kubeProxyReplacement: true
  k8sServiceHost: mule
  k8sServicePort: 6443

  l2announcements:
    enabled: true

  ingressController:
    enabled: true
    enforceHttps: true
    loadbalancerMode: dedicated

  operator:
    enabled: true
    replicas: 1
    rollOutPods: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 30s
        # labels:
        #   release: system
    dashboards:
      enabled: true
      label: grafana_dashboard
      annotations:
        grafana_dashboard_folder: Cilium

  # Dashboards for cilium-agent
  dashboards:
    enabled: true
    label: grafana_dashboard
    annotations:
      grafana_dashboard_folder: Cilium

  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: 30s
      # labels:
      #   release: system

  hubble:
    enabled: true
    relay:
      enabled: true
      rollOutPods: true
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
          # labels:
          #   release: system
    tls:
      enabled: false
    ui:
      enabled: true
      rollOutPods: true
      ingress:
        enabled: true
        className: cilium
        annotations:
          kubernetes.io/tls-acme: "true"
        hosts:
          - hubble.mukka.haus
        tls:
          - secretName: hubble-tls
            hosts:
              - hubble.mukka.haus
    metrics:
      enabled:
        - dns
        - drop
        - flow
        - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction
        - icmp
        - port-distribution
        - tcp
      serviceMonitor:
        enabled: true
        # labels:
        #   release: system
      dashboards:
        enabled: true
        # namespace: system
        label: grafana_dashboard
        annotations:
          grafana_dashboard_folder: Cilium
