{
 "title": "Smartctl-exporter",
 "description": "Metrics from smartctl-exporter",
 "tags": [ "smartctl" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(smartctl_device,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Devices count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_devices{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Missing devices",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_devices{instance=~\"$instance\"} - sum(smartctl_device{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Exit status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smartctl_device_smartctl_exit_status{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Media errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smartctl_device_media_errors{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Error log entries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smartctl_device_num_err_log_entries{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "SMART error log count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smartctl_device_error_log_count{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "SMART failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(1 - smartctl_device_smart_status{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Critical warnings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smartctl_device_critical_warning{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Device Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "smartctl_device{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "SMART overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "smartctl_device{instance=~\"$instance\"}"
    },
    {
     "expr": "smartctl_device_temperature{instance=~\"$instance\", temperature_type=\"current\"}"
    },
    {
     "expr": "smartctl_device_smartctl_exit_status{instance=~\"$instance\"}"
    },
    {
     "expr": "smartctl_device_smart_status{instance=~\"$instance\"}"
    },
    {
     "expr": "smartctl_device_power_on_seconds{instance=~\"$instance\"}"
    },
    {
     "expr": "smartctl_device_power_cycle_count{instance=~\"$instance\"}"
    },
    {
     "expr": "smartctl_device_interface_speed{instance=~\"$instance\", speed_type=\"current\"}"
    },
    {
     "expr": "smartctl_device_capacity_bytes{instance=~\"$instance\"}"
    },
    {
     "expr": "smartctl_device_capacity_blocks{instance=~\"$instance\"}"
    },
    {
     "expr": "smartctl_device_block_size{blocks_type=\"logical\", instance=~\"$instance\"}"
    },
    {
     "expr": "smartctl_device_block_size{blocks_type=\"physical\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "SMART attributes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "smartctl_device_attribute{instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "smartctl_device_temperature{instance=~\"$instance\", temperature_type=\"current\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Smartctl exit status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "smartctl_device_smartctl_exit_status{instance=~\"$instance\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "SMART passed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "smartctl_device_smart_status{instance=~\"$instance\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Power on seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "smartctl_device_power_on_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Power cycle count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "smartctl_device_power_cycle_count{instance=~\"$instance\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Write percentage used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "smartctl_device_percentage_used{instance=~\"$instance\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "NVMe capacity bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "smartctl_device_nvme_capacity_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Number of error log entries",
   "type": "timeseries",
   "description": "Contains the number of Error Information log entries over the life of the controller",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "smartctl_device_num_err_log_entries{instance=~\"$instance\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Number of media errors",
   "type": "timeseries",
   "description": "Contains the number of occurrences where the controller detected an unrecovered data integrity error. Errors such as uncorrectable ECC, CRC checksum failure, or LBA tag mismatch are included in this field",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "smartctl_device_media_errors{instance=~\"$instance\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "SMART error log count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "smartctl_device_error_log_count{instance=~\"$instance\", error_log_type=\"summary\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Critical warnings for state of controller",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "smartctl_device_critical_warning{instance=~\"$instance\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Interface speed (current)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "smartctl_device_interface_speed{instance=~\"$instance\", speed_type=\"current\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Interface speed (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "smartctl_device_interface_speed{instance=~\"$instance\", speed_type=\"max\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Capacity Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "smartctl_device_capacity_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Capacity Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "smartctl_device_capacity_blocks{instance=~\"$instance\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Bytes written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "smartctl_device_bytes_written{instance=~\"$instance\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Bytes read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "smartctl_device_bytes_read{instance=~\"$instance\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Block size (logical)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "smartctl_device_block_size{blocks_type=\"logical\", instance=~\"$instance\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Block size (physical)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "smartctl_device_block_size{blocks_type=\"physical\", instance=~\"$instance\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Available spare threshold",
   "type": "timeseries",
   "description": "When the Available Spare falls below the threshold indicated in this field, an asynchronous event completion may occur. The value is indicated as a normalized percentage (0 to 100%)",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "smartctl_device_available_spare_threshold{instance=~\"$instance\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Available spare",
   "type": "timeseries",
   "description": "Normalized percentage (0 to 100%) of the remaining spare capacity available",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "smartctl_device_available_spare{instance=~\"$instance\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  }
 ]
}