---
# Source: system/charts/sealed-secrets/templates/role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system-sealed-secrets-key-admin
  namespace: system
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-2.16.1
    app.kubernetes.io/instance: system
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.27.1
    app.kubernetes.io/part-of: sealed-secrets
  annotations:
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system-sealed-secrets-key-admin
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: system-sealed-secrets
    namespace: system
---
# Source: system/charts/sealed-secrets/templates/role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system-sealed-secrets-service-proxier
  namespace: system
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-2.16.1
    app.kubernetes.io/instance: system
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.27.1
    app.kubernetes.io/part-of: sealed-secrets
  annotations:
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system-sealed-secrets-service-proxier
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:authenticated
