---
# -- Replaces the name of the chart in the Chart.yaml file
nameOverride: ""

# -- Replaces the generated name
fullnameOverride: ""

image:
  # -- Repository to pull the image from
  repository: ghcr.io/cloudflare/ebpf_exporter
  # -- Image tag, if empty it will get it from the chart's appVersion
  tag: ""
  # -- Pull policy
  pullPolicy: IfNotPresent

# -- Secret name for pulling images from private repository
imagePullSecrets: []

# -- Additional pod annotations
podAnnotations: {}

# -- Privileges and access control settings for a container
securityContext:
  readOnlyRootFilesystem: true
  # ebpf_exporter requires elevated privileges
  privileged: true

# -- Node selection constraint
nodeSelector: {}

# -- Toleration for taints
tolerations: []

# -- Affinity rules
affinity: {}

# -- CPU/MEM resources
resources: {}

# -- Extra volume definition
extraVolumes:
  - name: kernel
    hostPath:
      path: /sys/kernel/debug
      type: Directory
  - name: modules
    hostPath:
      path: /lib/modules/
      type: Directory

# -- Extra volume mount definition
extraVolumeMounts:
  - mountPath: /sys/kernel/debug
    name: kernel
  - mountPath: /lib/modules/
    name: modules

# -- Command to run on start
command:
  - /ebpf_exporter

# -- Args to the command
args:
  - --config.dir
  - /examples/
  - --web.listen-address
  - 0.0.0.0:9435
  - --config.names
  - timers,uprobe,usdt,shrinklat,biolatency,accept-latency,bpf-jit,cachestat,cgroup,llcstat,raw-tracepoints,tcp-syn-backlog,tcp-window-clamps

service:
  labels: {}
  annotations: {}
  type: ClusterIP
  port: 9435
  portName: metrics

serviceMonitor:
  enabled: true
  labels: {}
  interval: 60s
  scrapeTimeout: 10s
  relabelings:
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: hostname
      regex: (.*)
      replacement: $1
