---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
    - 10.1.0.100-10.1.0.120

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  ipAddressPools:
    - default
